### ISSUE TITLE
Druid Shapeshifts display as "Human" in OHF normal

### ISSUE THREAD

**Issue by patmanpost** [SunstriderEmu/BugTracker#3223] opened 2020-05-03 12:25 UTC
**Druid Shapeshifts display as "Human" in OHF normal**

**To Reproduce**

1. Cast Shapeshift "x"  ...
2. Shape stays human and does not change to shapeshifted form

**Expected behavior**
Should change into shape :)

**Screenshots/videos**

![Human kitty in OHF](https://user-images.githubusercontent.com/64697317/80914136-ec9c0b80-8d49-11ea-930c-2ac23f545f83.png)

**Comment by beraus** [comment] 2020-05-05 00:49
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2788

**Closed by beraus** 2020-05-05 00:49 UTC
