### ISSUE TITLE
[Quest] Call of Water - Tel'Athlon The Impure adds are incorrectly hostile.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#2171] opened 2020-03-08 09:23 UTC
**Describe the bug**
In the fifth step of the Shaman's Call of Water quest a barrel is activated and two elementals spawn at the barrel while Tel'Athlon The Impure spawns across the stream.  The adds are supposed to be friendly and assist the player in attacking Tel'Athlon.  Instead they are hostile to the player.

**To Reproduce**

1. Click barrel to start event.
2. Get punched in the face.
3. Release and run back.

Call of Water, step 5,  includes comments noting that the adds should be friendly: https://www.wowhead.com/quest=9508/call-of-water

I am unable to find a specific page for the adds, which are simply called Water Spirit.  When I try to search that on Wowhead I get the phone book and many of the Water Spirit entries are incomplete.

**Expected behavior**
Water Spirtis should only punch the bad man.

**Screenshots/videos**
https://youtu.be/ZHkAvC23_c0
The Water Spirits in this video had spawned during my previous attempt.

**Additional context**

**Comment by Jerrythemagicdog** [comment] 2020-03-09 16:46
Thanks!

**Comment by r3dw1ng** [comment] 2020-05-06 19:34
The issue is still here, it makes the fight nearly impossible with an elemental spec

**Comment by Jerrythemagicdog** [comment] 2020-08-31 22:24
Thanks, fixed with next update.

**Closed by Jerrythemagicdog** 2020-08-31 22:24 UTC
Labels: confirmed, database, quest
