### ISSUE TITLE
Cant see NPC's in Auchenai Crypts.

### ISSUE THREAD

**Issue by criljan** [SunstriderEmu/BugTracker#3054] opened 2020-04-19 08:47 UTC
**Describe the bug**
I cant see the NPC's at the entrance of Auchenai Crypts anymore. There is a quest chain to be able to see and interact with them (completed and done). Now I am on the quest "Everything will be allright" and it's completed. But now i cant turn it in. 

Quest: https://wowhead.com?quest=29596/the-end-of-the-exarch

Thanks!

Christopher

**Comment by Sheikthecatman** [comment] 2020-04-22 19:24
The issue is that [Greatfather Aldrimus](https://db.endless.gg/?npc=19698) cannot be seen as [Commune With the Ancestors](https://db.endless.gg/?spell=32649) is missing, reason as to why it disappears is unknown. Would be great to receive steps on how to reproduce the disappearance of the aura.

Greatfather Aldrimus](https://db.endless.gg/?npc=19698) needs to be seen to continue with [Everything Will Be Alright](https://db.endless.gg/?quest=10164)

@criljan If you wish to turn in the quest, create an in-game ticket and support may assist you with a temporary solution.

**Comment by criljan** [comment] 2020-04-23 14:24
Yes exactly and to obtain the quest you must have the aura aswell. Since it was Greatfather Aldrimus i took it from. Cant you like see somehow if I have done the quest chain to obtain the aura? And then activate it on the character? Because I need to see the NPC's so I can repair and stuff. 

Best, 
Christopher

**Comment by Sheikthecatman** [comment] 2020-04-23 19:16
As stated in the previous comment, please create an in-game ticket and support may assist you with a temporary solution.

**Comment by criljan** [comment] 2020-04-23 20:34
yes but a temporary solution wont do here. Because the reason why i did
this q-chain was to be able to interact with the npc's there..

Den tors 23 apr. 2020 kl 21:16 skrev Sheikthecatman <
notifications@github.com>:

**Comment by Sheikthecatman** [comment] 2020-05-04 16:19
Fixed in [32948668ce04c51a61d62bea890955d1e43dec77](https://github.com/kelno/sunstrider-scripts/commit/32948668ce04c51a61d62bea890955d1e43dec77)

**Closed by Sheikthecatman** 2020-05-04 16:19 UTC
Labels: confirmed, quest
