### ISSUE TITLE
My account has been canceled for using BOT when I am seeing that it is allowed

### ISSUE THREAD

**Issue by Troxwa** [SunstriderEmu/BugTracker#3408] opened 2020-05-17 13:23 UTC
Sorry, the translation is from google.

I know it's not a bug but I don't know where to expose it. I have been reading the forum for a couple of days and a little over 1 month, since I decided to use the BOT, the server rules and have never found anything against the use of BOT. So why has my account been canceled indefinitely? I only use it to farm which according to the forum is allowed, what is the way to solve it?
Thank you

**Comment by InhumanGM** [comment] 2020-05-17 15:39
Closing this issue as it is not a bug. You can reach out to Support Manager Simon (Endless Simon#1337) on Discord for ban appeals.

**Closed by InhumanGM** 2020-05-17 15:39 UTC

**Comment by Troxwa** [comment] 2020-05-17 19:46
Simon does not clarify anything, he just tells me that in endless it is illegal to use them and that there is nothing more to talk about. however there is nothing written on the subject. just like on the server page there are writes what can and cannot be done about the bot there is nothing written

**Comment by Godmatik** [comment] 2020-05-17 20:56
I can't think of a single major server that allows botting, I don't know why you think it would be different here.

**Comment by bjh368** [comment] 2020-05-26 21:54
![image](https://user-images.githubusercontent.com/59749446/82954071-43dd7680-9fac-11ea-9762-7012d049c2e5.png)
