### ISSUE TITLE
soul shards from nothing

### ISSUE THREAD

**Issue by domnoob** [SunstriderEmu/BugTracker#4410] opened 2020-10-30 19:11 UTC
pets should not return a soul shard when they are separated from the warlock **while in battlegrounds**
i get bags full of shards in one afternoon, because the pet can't catch up while i jump off a cliff, or it chases away an enemy or whatever.
it's created from nothing (no shard consumed), it should not refund a shard.

**Comment by cbiprw** [comment] 2020-11-09 14:36
after the latest restart, if i get separated from my pet (btw it happens a lot due to pathing issues, this is serious problem) inside a battleground it gives me a soul shard instead and no pet, when i try to summon back.
when you first enter a bg you can summon fine, to reproduce put pet on stay to separate it from warlock and then try to summon

**Comment by cbiprw** [comment] 2020-11-09 19:17
it seems it's more wider problem...
confirmed this multiple times:
die while pet alive and in range
res
receive shard
then if i die again i might spawn with pet

**Comment by kelno** [comment] 2020-11-18 14:10
Thank you, fixed with next update

**Closed by kelno** 2020-11-18 14:10 UTC
Labels: confirmed, core
