### ISSUE TITLE
Parry haste not working

### ISSUE THREAD

**Issue by Swindellite** [SunstriderEmu/BugTracker#2443] opened 2020-03-20 22:21 UTC
After a parry the player's next auto attack should be 50% faster. This does not work.

**Comment by Notmelody** [comment] 2020-03-21 06:26
Confirmed for npc mobs

**Comment by oldspices** [comment] 2020-03-21 21:18
not all are supposed to do that tho

**Comment by TheMoneyHater** [comment] 2020-03-22 11:25
If anyone is playing a tank try it on bosses since not all normal mobs have a parry chance in the game.

**Comment by kelno** [comment] 2020-04-09 06:30
Fixed with next update

**Closed by kelno** 2020-04-09 06:30 UTC
