### ISSUE TITLE
Skywing

### ISSUE THREAD

**Issue by Pecka69** [SunstriderEmu/BugTracker#2581] opened 2020-03-27 17:31 UTC
https://www.wowhead.com/quest=10898/skywing

Skywing NPC stand in the right place, but doesn't give the quest.

**Comment by blblblaz** [comment] 2020-03-30 13:08
yeah confirmed, the issue is related to someone failing the quest and Skywing not resetting properly, thanks for the report

**Comment by Macumbafeh** [comment] 2020-03-31 13:34
+1, wanted to do the quest and couldn't : /

**Comment by Jerrythemagicdog** [comment] 2020-08-13 00:20
Thanks, fixed with next update.

**Closed** 2020-08-13 00:20 UTC
Labels: confirmed, quest
