### ISSUE TITLE
Warrior Execute not consuming a sweeping strikes charge 

### ISSUE THREAD

**Issue by grifwow** [SunstriderEmu/BugTracker#2434] opened 2020-03-20 17:04 UTC
Sweeping strikes is supposed to transfer damage from a primary target to a secondary, but execute is not being counted as damage that gets copied over and still only hits one target even if sweeping strikes is active. It's a big dps loss for fury warriors.

**Comment by Jerrythemagicdog** [comment] 2020-03-20 17:09
Thanks, duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/1177

**Closed by Jerrythemagicdog** 2020-03-20 17:09 UTC
