### ISSUE TITLE
[Hellfire Peninsula] Mag'har Ancestral Beads dont drop

### ISSUE THREAD

**Issue by rico-zellmann** [SunstriderEmu/BugTracker#1987] opened 2020-03-01 16:28 UTC
[Mag'har Ancestral Beads](https://tbcdb.com/?item=23589) dont drop. So the quest [Makuru's Vengeance](https://tbcdb.com/?quest=9424) and all followups cant be completed.

**Comment by Godmatik** [comment] 2020-03-02 06:29
Confirmed.

**Comment by call69** [comment] 2020-03-02 13:36
Please fix asap this is important pre-q for the kurenai , many quests in zanga an nagrand are not accesible because of this.

**Comment by SUN-Leekie** [comment] 2020-03-04 23:41
A fix has been applied yesterday.

**Closed by SUN-Leekie** 2020-03-04 23:41 UTC
