### ISSUE TITLE
Potion/Healthstone + Druid Form Bug

### ISSUE THREAD

**Issue by Ashlander636** [SunstriderEmu/BugTracker#2928] opened 2020-04-12 14:29 UTC
**Describe the bug**
Before yesterday's (11/04/2020) update everything was working perfectly fine, but since then druids aren't able to macro consumable+form cast which allows them to stay in form after using one. I believe you added some kind of delay after every action and it absolutely broke the class.
**To Reproduce**
Make a Druid. Get potion. Write macro
/use Super Healing Potion
/cast Moonkin Form
and see what happens
**Expected behavior**
If you're in form. not CCed and off-GCD you should cast simultaneously pot+form
**Additional context**
https://www.wowhead.com/forums&topic=35430 

1st and 4th post for proof that it has always worked this way (on retail and any other private TBC server)

**Comment by oldspices** [comment] 2020-04-12 22:35
I also noticed someething weird with my potion/bearform macro where i saw my self out of bearform which scared me - this shouldnt happen

**Comment by recreantus** [comment] 2020-04-13 01:49
Yes, I can confirm this bug. I was just about to write a report myself. Before tonight's raid I was able to use my macros that allow me to exit cat form, use a potion and shift back into cat form, all in one press. The macro looks like this: 
/script local gcd=GetSpellCooldown("Cat Form"); if gcd==0 then CancelPlayerBuff("Cat Form") end;
/stopmacro [stance:2]
/use Haste Potion
/cast Cat Form

And now when I use it, it shifts me out of form, consumes the potion but leaves me with a 1 second global cooldown (there shouldn't be a cooldown when either shifting out or using a potion), which entirely disrupts the rotation and had me spamming Healing Touch instead of Shred before I realized what was going on.

Please fix this and turn it back like it was a few days ago, and how it should be.

**Comment by krashkneck** [comment] 2020-04-13 12:45
i also noticed some weird stuff with my pot+bear form macros. i'm using ones similar to the above but for stoneshield potion, healthstone and healing potion and they all worked fine until yesterday. now they just put me in normal form instead of going back to bear, which really sucks when tanking...

**Comment by notsofamous** [comment] 2020-04-13 21:24
Can confirm, this is a **very big bug** for feral druids.

**Comment by oldspices** [comment] 2020-04-13 23:54
plz fix:)

**Comment by recreantus** [comment] 2020-04-18 14:01
can we please get a dev to acknowledge this issue?

**Comment by kelno** [comment] 2020-05-02 11:45
Thanks, fixed with next server update

**Closed by kelno** 2020-05-02 11:45 UTC
Labels: confirmed, core
