### ISSUE TITLE
Draenei paladin redemption quest unavailable once abandoned

### ISSUE THREAD

**Issue by Mrprika1950** [SunstriderEmu/BugTracker#3785] opened 2020-06-23 18:32 UTC
I abandoned the paladin redemption quest when it was level appropriate. Afterwards went to paladin trainer Jol in Exodar to pick up the quest, however the quest was unavailable.

**Comment by InhumanGM** [comment] 2020-06-23 19:27
Duplicate of #3255

**Closed by InhumanGM** 2020-06-23 19:27 UTC
