### ISSUE TITLE
[Druid] Talent - Primal Fury - Not always granting additional Combo Point

### ISSUE THREAD

**Issue by Chriski** [SunstriderEmu/BugTracker#935] opened 2019-03-30 10:09 UTC
**Description:**

When spec'd into 2/2 of Primal Fury (ID: 16961/37117), no additional Combo Point is generated upon delivering a critical strike with a CP generating ability

**Current behaviour:**

Appears to be randomly generating a combo point when delivering a critical strike with a CP generate ability. This should be 100% of the time when spec'd into 2/2

**Expected behaviour:**

When spec'd into 2/2 Primal Fury (ID: 16961/37117), upon delivering a critical strike with a CP generating ability (Mangle, Claw, Rake) only sometimes an additional combo point is being generated (should be 100% of the time with 2/2)

**rev. hash/commit:**  
Sunstrider rev. 10800 (52a569be5ae0+) 2019-03-28 22:17:07 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Orcfootstool** [comment] 2019-04-16 06:41
This is still occurring, any updates?

**Comment by Orcfootstool** [comment] 2019-04-24 07:38
Any chance this can be looked at, becoming increasingly annoying to deal with.

**Comment by Orcfootstool** [comment] 2019-04-30 13:28
So I believe I've figured out whats going on with this issue. Sometimes when respeccing, clicking once in Primal Fury to apply 1/2 rank will instead do 2/2. This causes Primal Fury to bug out and not apply the extra combo point correctly. Resolving this has so far been to relog then respec again, you should then be able to click Primal Fury once to correctly apply 1/2 rank then click once again to fill 2/2. You should then always generate an extra combo point on combo point crits.

**Comment by kelno** [comment] 2019-05-25 07:39
This is probably fixed with 11418 but not 100% sure as I couldn't reproduce the problem in the first place.

**Comment by Jerrythemagicdog** [comment] 2019-07-06 14:41
fixed

**Closed by Jerrythemagicdog** 2019-07-06 14:41 UTC
Labels: doublechecked, gamebreaking, spells, testfix
