### ISSUE TITLE
Arcatraz Sentinel is unlootable hence the Parttern Arcanoweave Bracers is unattainable.

### ISSUE THREAD

**Issue by xgztylm** [SunstriderEmu/BugTracker#4099] opened 2020-08-15 16:23 UTC
**Describe the bug**
 In the instance Arcatrz, one of the robot mob: Arcatraz Sentinel is unlootable hence the Parttern Arcanoweave Bracers is unattainable.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://tbc-twinhead.twinstar.cz/?item=21905

**Expected behavior**

Make the mob lootable and drop the parttern we need as it should be in TBC.

**Screenshots/videos**

**Additional context**

**Comment by MianLavanAelin** [comment] 2020-08-16 14:07
Confirming, probably the cause is that we start fight at 40% hp and it does not count towards player's credit. 
Or the AI for suicide is incorrect, it uses the suicide spell on death in which case it also does not credit the player. 
Please fix this one, the pattern is very important.

**Comment by xgztylm** [comment] 2020-08-19 15:45
Any lovely GM can confirm this or reply?

**Comment by BasedForfrost** [comment] 2020-08-19 16:29
Yeah a friend of mine has been trying to farm the pattern on a daily basis and couldn't believe how bad his luck was and neither could I. Wasn't until I did an Arcatraz run with him that I realized no one ever looted a sentinel at any point in the run.

**Comment by xgztylm** [comment] 2020-08-19 22:04
Yes buddy that's exactly what happened to me many runs. And if u search it online you will notice it's a very common Bug in private servers, it happens in other servers too.

**Comment by gdubeau** [comment] 2020-08-23 23:13
I basically ran arctraz on my warlock for that pattern specifically to almost exalted and that pattern never dropped. This would make sense why. Very frustrating

**Comment by Jerrythemagicdog** [comment] 2020-09-04 05:41
Thanks, fixed with next update.

**Closed by Jerrythemagicdog** 2020-09-04 05:41 UTC
Labels: confirmed
