### ISSUE TITLE
the quest 'Kindness" BUG

### ISSUE THREAD

**Issue by doommonster** [SunstriderEmu/BugTracker#2843] opened 2020-04-09 12:48 UTC
**Describe the bug**

no matter how many corpses you put on the ground doesn`t work i know at least 20 ppl with the same problem
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment] 2020-05-03 02:11
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2549

**Closed** 2020-05-05 00:08 UTC
