### ISSUE TITLE
[Addons] Gladdy be broken

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1408] opened 2019-09-21 13:17 UTC
**Describe the bug**
Title

**To Reproduce**
~~Unknown steps to reproduce right now but the clue here is that it either bugs out for an entire arena match or it works fine.~~

It appears it can happen mid-arena match as well and stop tracking.

Example: https://www.twitch.tv/videos/484073474?t=02h04m02s

Druid gets feared - DR isn't tracked, then Druid gets stunned and DRs don't get tracked. At the same time seems to be working for Rogue (Gladdy frame)

**Comment by hufsa** [comment] 2019-09-21 19:24
Should try to reproduce with combat log shown and compare the combat log to when it's working.

**Comment by ramadansteve** [comment] 2019-09-25 17:09
we've done some testing and this is what we found:
1. the issue is probably not about DR tracking addons, its about Gladdy specifically (other addons might also be affected by this issue though)
2. not only DR module gets bugged but all of them (HP/MP, castbars, auras (cc durations on top of class icons, cooldowns) except Trinket CD
3. the bug occurs separately for each gladdy frame (arena1/2/3) e.g. arena1 can get bugged and arena2 will still work fine
4. once its bugged it doesn't go back to normal until the end of an arena match
5. /reload fixes it
6. seems like it's not related to the work of combat log
7. this is a 'new bug' (was not a thing in the early days on ptr)

**Comment by kelno** [comment] 2019-09-25 17:11
Thanks a lot that's very helpful

**Comment by kelno** [comment] 2019-10-04 00:35
Fixed with https://github.com/kelno/sunstrider/commit/ca8c187fb69332a1abb7cd9687bd8addad5f327e

**Closed by kelno** 2019-10-04 00:35 UTC
Labels: confirmed
