### ISSUE TITLE
[Hunter][Spell] Melee autoattack queuing gets stuck after an unsuccessful raptor strike, only gets resolved after relog

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1566] opened 2019-12-27 23:47 UTC
https://streamable.com/f25i7 is the most reproducible clip I could make that shows the queuing getting stuck. Though I have had this occur several times while leveling a hunter each occurrence seemingly due to different events.

I have also seen this occur on a rogue and warrior, but hasn't required relogging to fix the issue and seems to fix itself after retargeting so relatively minor in comparison. 

https://github.com/SunstriderEmu/BugTracker/issues/1376 slightly related.

**Comment by Jerrythemagicdog** [comment] 2019-12-28 03:09
Thanks!

**Comment by kelno** [comment] 2020-01-02 14:50
Definitely happens sometimes but I can't manage to reproduce it atm

**Comment by kelno** [comment] 2020-01-02 15:32
Fixed in 13031
In this example, the melee state enabling would fail because the target was evading, but the server wouldn't correctly tell the client to disable the melee state after that.

**Comment by Jerrythemagicdog** [comment] 2020-01-06 23:33
Some more information about that: 
https://gfycat.com/CheerfulRevolvingBasilisk

Seems to not be fixed entirely as detargeting a creature doesn't stop autoattacking it.

**Comment by kelno** [comment] 2020-01-07 04:03
Is this still relates to Raptor Strike ?

**Comment by Jerrythemagicdog** [comment] 2020-01-07 04:26
No, this is regular autoattacks but it's related

**Comment by Jerrythemagicdog** [comment] 2020-01-07 04:34
Moved to its separate issue.

**Closed by Jerrythemagicdog** 2020-01-07 04:34 UTC
Labels: confirmed, core
