### ISSUE TITLE
free falling off zeppelin and died bug

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3235] opened 2020-05-04 19:44 UTC
**Describe the bug**
I was sneaking in the lower cabin on the Gromgol to UC zeppelin. Reason I was sneaking was allys were killing off everyone in Gromgol and one of them was on the zeppelin. The zeppelin started to leave, as it was about to leave the STV zone, I was freefalling all of a sudden to my death.

**To Reproduce**
1. Get on the zeppelin from Gromgol to UC
2. Sneak on the lower deck
3. wait as it crosses the STV border

**Expected behavior**
I should arrive at the UC zeppelin tower safely.

**Comment by beraus** [comment] 2020-05-05 02:13
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/445

**Closed by beraus** 2020-05-05 02:13 UTC
