### ISSUE TITLE
The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by phatload51** [SunstriderEmu/BugTracker#4086] opened 2020-08-12 01:41 UTC
Obtaining the flawless arcane essence is impossible since the NPC you need to talk to, Sar'this, is channeling something and you can't interact with them.

**Comment by beraus** [comment] 2020-08-12 02:06
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3718

**Closed by beraus** 2020-08-12 02:06 UTC
