### ISSUE TITLE
Mage Quest: Investigate the Blue Recluse in Stormwind doesnt work.

### ISSUE THREAD

**Issue by d0mekate** [SunstriderEmu/BugTracker#3075] opened 2020-04-21 09:37 UTC
After accepting the quest in SW you take the two items from the table in mage tower stormwind. After that you go to the tavern (blue recluse next to the tower). The idea is to use the scroll in the taver to trigger these elementals and than catch them. BUT it doesnt work ive used the scroll everwhere in tavern no elemental spawns. Please check this Class Quests are important.

**Comment by beraus** [comment] 2020-04-21 13:05
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1907

**Closed** 2020-05-05 00:10 UTC
