### ISSUE TITLE
Hunter pet bar

### ISSUE THREAD

**Issue by hillo84** [SunstriderEmu/BugTracker#2310] opened 2020-03-14 13:55 UTC
**Describe the bug**
Hunter pet bar sometimes disappears after the pet dies and you resurrect it.

**To Reproduce**

1. Pet dies
2. Cast Revive Pet on the pet
3. Pet resurrects but with no pet bar and also keybinds for commanding the pet don't work.
4. The pet bar reappears after doing /reload

Spell: https://classic.wowhead.com/spell=982/revive-pet

**Expected behavior**
Pet should resurrect and the pet bar should reappear normally.

**Comment by SUN-Leekie** [comment] 2020-03-14 18:01
Hi, I cannot reproduce for now, can you please provide more information or a video?
Thanks

**Comment by beraus** [comment] 2020-06-01 01:05
This issue should be fixed now.

**Closed by beraus** 2020-06-01 01:05 UTC
Labels: question
