### ISSUE TITLE
Master of Elixirs Quest cant be completed

### ISSUE THREAD

**Issue by emparn94** [SunstriderEmu/BugTracker#2579] opened 2020-03-27 16:40 UTC
i cant turn in the Master of Elixirs quest to Lorokeem.

![elixir1](https://user-images.githubusercontent.com/61750866/77778874-fc8d4500-7051-11ea-8bac-03eee9df489b.png)
![elixir2](https://user-images.githubusercontent.com/61750866/77778889-0020cc00-7052-11ea-83d4-6ceac56a6d5f.png)

**Comment by Godmatik** [comment] 2020-03-27 17:24
Putting them in your bank and taking them out I heard is a work-around

**Comment by blblblaz** [comment] 2020-03-30 12:32
that's a general issue, not specific to that quest, I can't reproduce, but a decent amount of people have reported similar issues with random quests so I am confirming it

**Comment by beraus** [comment] 2020-05-31 01:20
This issue is fixed now.

**Closed by beraus** 2020-05-31 01:20 UTC
Labels: confirmed, quest, research needed
