### ISSUE TITLE
Spiritual Attunement doesn't work

### ISSUE THREAD

**Issue by DollpartsFTP** [SunstriderEmu/BugTracker#2101] opened 2020-03-05 01:04 UTC
**Describe the bug**
Paladin baseline ability Spiritual Attunement doesn't work.

**To Reproduce**
Get healed.
If the heal brings you to full, you gain 0 mana, no matter how big the heal is.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior*
Expected to act like the talent says.. Give mana back on getting healed.

**Additional context**
GAMEBREAKING FOR PROT PALADINS

**Comment by Godmatik** [comment] 2020-03-05 01:16
Works fine for me... are you being overhealed?

**Comment by SUN-Leekie** [comment] 2020-03-05 01:17
I saw it working yesterday. As Godmatik implied, receiving overheals should'nt give you mana which is working as intended in this case.

**Comment by DollpartsFTP** [comment] 2020-03-05 12:45
It's not overheals, it's not giving the correct amount of mana. When you receive a 6500 raw heal, and receive 31 mana, that's not correct, no matter how you try to tell people otherwise. It's not working correctly, the values are way off (Like seemingly everything else on a Paladin, in case you haven't noticed from the bug reports)

**Comment by SUN-Leekie** [comment] 2020-03-05 13:21
Thanks for the details. Note that saying "x is not working" and "x is not working *properly*" is really different for what testers/devs should look for.

**Comment by SUN-Leekie** [comment] 2020-03-07 05:10
Just wrote an automated test and it's working as intended.
Closing until further proofs are provided.

**Closed by SUN-Leekie** 2020-03-07 05:10 UTC
Labels: question

**Comment by DollpartsFTP** [comment] 2020-03-09 14:58
Ignoring core class mechanics, best way to run a server. But hey, Alliance have perks THAT'S AWESOME RIGHT WHO NEEDS BASIC CLASS MECHANICS.

**Comment by Godmatik** [comment] 2020-03-09 15:42
Lol someone is salty.

**Comment by SUN-Leekie** [comment] 2020-03-09 16:33
@DollpartsFTP  If you could provide a video of it happening, that would help a lot. Everything I tried to reproduce it did not work. I even saw it working playing on the server...
