### ISSUE TITLE
Whelps of the wyrmcult

### ISSUE THREAD

**Issue by ugyanakkor** [SunstriderEmu/BugTracker#2924] opened 2020-04-12 09:38 UTC
This q in BEM is bugged, i got 12 nets, i have to colllect 10 whelps, and lot of times it is not collect when i hit it with the net, so when im out of nets, i got 6-8 whelps, and im not able to do this q, i tried 3 times and every time bugged. When i abandon the q and accept it again, i lost my collected whelps.

**Comment by bisquiit** [comment] 2020-04-13 14:43
confirming bugged quest.

**Comment by beraus** [comment] 2020-04-21 23:06
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2159

**Closed** 2020-05-31 01:32 UTC
Labels: quest
