### ISSUE TITLE
[BUG] Water Shield/Lightning Shield stacks

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2828] opened 2020-04-09 05:36 UTC
Water Shield is consuming procs from auras when it should not. 

Simple things like Gruul's mass silence ability is proccing a water shield charge, shamans almost hardly run out of mana on that fight as a result.

Video proof from TBC - Fighting against Netherspite, the periodic shadow aura ticks do not consume water shield stacks. On Sunstrider, it currently does.

https://www.youtube.com/watch?v=0q-p4W3dJcM

**Comment by Jerrythemagicdog** [comment] 2020-04-10 05:14
Duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/1794

**Closed by Jerrythemagicdog** 2020-04-10 05:14 UTC
