### ISSUE TITLE
Weird visual bug on blood elf bandit

### ISSUE THREAD

**Issue by KingKC612** [SunstriderEmu/BugTracker#1542] opened 2019-12-20 04:17 UTC
![WoWScrnShot_121919_220310](https://user-images.githubusercontent.com/32748063/71229973-54771b80-22ad-11ea-91d7-f43f70c69dd4.jpg)

**Comment by Jerrythemagicdog** [comment] 2019-12-20 23:08
I can't reproduce this exact effect.
To dev:
There's definitely a brief effect like this when a creature with Stealth casts it on respawn immediately (through SAI for example). This one in particular has it on reset. 
Perhaps we could try adding a little bit of delay on a creature respawn and when it does its first action, similarly to how we have it for summons currently.

**Comment by kelno** [comment] 2019-12-21 11:16
That's kinda pretty !

**Comment by kelno** [comment] 2019-12-21 11:17
Looks like he recast stealth many many times per second

**Comment by kelno** [comment] 2019-12-21 13:56
Changed this guy AI completely, should be fixed

**Closed by kelno** 2019-12-21 13:56 UTC
Labels: confirmed
