### ISSUE TITLE
Scryers bloodgem and Xi'ri's Gift cannot be used

### ISSUE THREAD

**Issue by joepro1234** [SunstriderEmu/BugTracker#2366] opened 2020-03-16 22:27 UTC
**Describe the bug**
The on use effect of Scryers Bloodgem can't be triggered after using Xi'ris gift. Or wise versa.

**To Reproduce**
Equip trinkets in slots 13 and 14. Drag trinkets to castbar and click them back to back after trinket effects. 

Item1: https://www.wowhead.com/item=29132/scryers-bloodgem
Item2: https://www.wowhead.com/item=29179/xiris-gift

**Expected behavior**
The trinkets are expected to be able to be triggered back to back after the first trinket has been used.

**Comment by Djakamoe** [comment] 2020-04-06 02:07
very unfortunate for this, I hope they fix this

**Comment by beraus** [comment] 2020-05-04 23:36
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087

**Closed by beraus** 2020-05-04 23:36 UTC
