### ISSUE TITLE
Hunter 2pc T5 Set bonus causing threat.

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#3736] opened 2020-06-18 12:46 UTC
**Describe the bug**
As mentioned in the title, the 2 piece set bonus for Hunter Tier 5 armor is generating threat for the hunter. It should not.

**To Reproduce**
1. Equip 2 pieces of T5
2. Attack a pack of creatures (without viper on, because it also incorrectly causes passive threat)
3. Do some damage to one target, then watch most of them run at you and ignore your pet.

Discussion regarding T5:
https://www.wowhead.com/item-set=652/rift-stalker-armor
> 36 | Xeri on 2008/02/23 (Patch 2.3.3)The healing generates no threat for the hunter or pet.

**Expected behavior**
As suggested above, the set bonus should not generate threat for the hunter or the pet.
Also Aspect of the Viper is _still_ generating threat.

**Comment by Jerrythemagicdog** [comment] 2020-06-19 01:30
Can't reproduce the 2 piece T5 bonus causing threat, it has the correct attribute to not cause threat as well.
https://streamable.com/c0txtn

Aspect of the Viper fixed with next update.

**Closed** 2020-06-21 15:00 UTC
Labels: question
