### ISSUE TITLE
Whirlwind and sweeping strikes

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1431] opened 2019-09-24 10:34 UTC
The Problem:

Whirlwind currently behaves the same way as cleave, whitch means that whirlwind hit on secondary target causes SS proc on main target, resulting in 4 hits in total. Which results in 2 charges of SS used.

https://youtu.be/ETOgLCgYeeI

How it should work: 

Whirlwind should not proc SS from secondary target hit. There should be only 3 hits from Whirlwind+SS not 4 hits. WW should consume only 1 SS charge.

Meaning: Main target gets hit from WW, secondary target gets hit from WW, secondary target gets hit from SS caused by hit on main target. No additional SS hit on main target. 

https://youtu.be/2tFLsUaxEIM?t=12s
After WW+SS there were 3 hits in total. 2k crit on main target (rogue) then 1.5k SS crit and 1.3k hit on warrior.

https://youtu.be/3rbd02jJXy8?t=4m32s

Main target dies on WW hit, but you can see the stacks of SS here. Before Whirlwind warrior had 7 stacks, after Whilrwind warrior had 6 stacks. So only 1 charge got consumed.

https://youtu.be/NKIGBZ0jjyc?t=1m4s

(play it on 0.25 speed)
After warrior used WW you can see it consumed only 1 charge, and then another charge was consumed by white attack.

**Comment by Jerrythemagicdog** [comment] 2019-09-24 22:14
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/165

**Closed by Jerrythemagicdog** 2019-09-24 22:14 UTC
