### ISSUE TITLE
Aspect of the viper

### ISSUE THREAD

**Issue by avclol** [SunstriderEmu/BugTracker#3401] opened 2020-05-17 08:37 UTC
Hello, The aspect of the viper Is bugged. The mana regeneration isn't working at All.  Please take another look. Even with x30 intellect on both weap still you get oom Instant in Arena. Please don't delete my report and just watch the other hunters answers. In the Official server we were able to see the mana regeneration rising while our mana is low. '' The lower the hunter's current mana, the more mana will be regenerated. Only one Aspect can be active at a time.'' This part of the spell isn't working. Please make a look into it.

**Comment by InhumanGM** [comment] 2020-05-17 16:10
Duplicate of #2679

**Closed by InhumanGM** 2020-05-17 16:10 UTC
Labels: spells
