### ISSUE TITLE
[Quest]Seal of Ascension  (Emberstrife)

### ISSUE THREAD

**Issue by someguy113** [SunstriderEmu/BugTracker#2685] opened 2020-04-02 04:52 UTC
The black dragon named Emberstrife has no controlled ability Flames of the Black Flight.
The UBRS attunement quest Seal of Ascension is impossible to complete.

**Comment by artieau** [comment] 2020-04-29 03:52
Duplicate of #2382

**Closed by artieau** 2020-04-29 03:52 UTC
