### ISSUE TITLE
Paladin Class quest is not working

### ISSUE THREAD

**Issue by kealthas06** [SunstriderEmu/BugTracker#3427] opened 2020-05-18 15:35 UTC
**Describe the bug**
<İn order to Complete the last paladin quest ''true masters of light'' you have to kill a mob but it doesn't turn enemy>

**To Reproduce**
<very easy just make the mob killeable once you use the item>

Item: https://www.wowhead.com/item=24287/extinguishing-mixture
Quest: https://www.wowhead.com/quest=9737/true-masters-of-the-light
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**
<!--- it is a very easy quest to fix and i spent 500g to this quest please help

**Comment by InhumanGM** [comment] 2020-05-18 17:00
Duplicate of #2669

**Closed by InhumanGM** 2020-05-18 17:00 UTC
