### ISSUE TITLE
[Quest]Investigate the Blue Recluse

### ISSUE THREAD

**Issue by itsithilien** [SunstriderEmu/BugTracker#3336] opened 2020-05-12 11:04 UTC
**Describe the bug**

[Quest]Investigate the Blue Recluse
https://tbcdb.com/?quest=1920

cannot be finished due to bugged item

Chest of Containment Coffers
https://tbcdb.com/?item=7247

cannot be used to capture stunned Rift Spawn as advertised

it reads:
you can't do that yet
****

**Comment by itsithilien** [comment] 2020-05-13 00:37
![WoWScrnShot_051220_124817](https://user-images.githubusercontent.com/65227440/81758617-a883d600-94c2-11ea-8b58-f63dc4e797b2.jpg)

**Comment by InhumanGM** [comment] 2020-05-14 13:10
When the Rift Spawn reaches a certain health threshold, it then becomes 
stunned. When it becomes stunned, you should be able to use the item to capture it, but 
it returns an error "You can't do that yet".

This is the expected behavior.
https://www.youtube.com/watch?v=3u6bbzflEDU

**Comment by Sheikthecatman** [comment] 2020-05-14 20:17
Duplicate of #1907

**Closed by Sheikthecatman** 2020-05-14 20:17 UTC
Labels: bug, confirmed, quest
