### ISSUE TITLE
Rocket Boots Xtreme has 100% malfunction rate

### ISSUE THREAD

**Issue by PekelZoda** [SunstriderEmu/BugTracker#2912] opened 2020-04-11 20:18 UTC
**Describe the bug**

The Rocket Boots Xtreme (from the pattern from Steamvaults) ALWAYS malfunction, stunning the using for ~3 seconds. 

**To Reproduce**

1. Equip a pair of Rocket Boots Xtreme. (and wait 30 sec)
2. Activate Rocket Boots Xtreme.
3. Notice how they malfunction and stun you.
4. Wait 5 minutes for the CD of the boots. 
5. Repeat steps 2 through 4 nine more times, for a total of ten activations with 100% malfunction rate. 

Item: https://tbc-twinhead.twinstar.cz/?item=23824

**Expected behavior**

I believe malfunction rate should be lower, but I don't know how low, exactly. Somewhere around 10-20% I believe is correct. 

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment] 2020-05-05 00:02
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2500

**Closed by beraus** 2020-05-05 00:02 UTC
