### ISSUE TITLE
At War, Quest Issue 

### ISSUE THREAD

**Issue by Aurorathe** [SunstriderEmu/BugTracker#2887] opened 2020-04-10 20:51 UTC
I am unable to complete the quest "Getting Down to Business". The issue is that when i cannot fight the mobs required for the quest. The mobs that need to be killed are part of the 'Netherwing' faction. I am friendly with this faction. When i click "At War" in the reputation tab i still cannot fight the associated mobs. Thank you for reading this.

**To Reproduce**
1.Be friendly or higher with the 'Netherwing' faction
2.Attempt to fight 'Netherwing' mobs.

Mob: https://www.wowhead.com/npc=20332/nether-dragon
Mob: https://www.wowhead.com/npc=18877/nether-drake
Quest: https://www.wowhead.com/quest=10271/getting-down-to-business

**Expected behavior**
I would click the "At War" button on the reputation tab, and be able to fight the mobs associated with the quest.

**Screenshots/videos**
![WoWScrnShot_041120_064449](https://user-images.githubusercontent.com/49894880/79021897-1c7b4780-7bc0-11ea-934c-bc2a1fd6283f.jpg) (Clicking at war)
![WoWScrnShot_041120_064507](https://user-images.githubusercontent.com/49894880/79021900-1f763800-7bc0-11ea-95e0-b8631645617a.jpg) (Attempting to fight mob, shows invalid target in combat log. Also right clicking with auto attack shows the red flash on the targets circle but goes back to green.)

**Additional context**
I assume this would bug out other quests which require you to fight mobs part of the 'Netherwing' faction.

**Comment by beraus** [comment] 2020-05-24 23:09
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3182

**Closed by beraus** 2020-05-24 23:09 UTC
Labels: quest

**Comment by Morrigan83** [comment] 2020-07-14 08:02
could you please fix thus bug where people friendly with netherwing can't attack the dragons after clicking at war ? I been trying to farm scales for my 3 piece netherscale armor and it's impossible.  you can't just close it.

**Comment by Orivanz** [comment] 2020-07-31 23:04
I was told to submit my bug here, having the same issue. Any fix in place? I'd be fine with having my rep knocked down at this point.
