### ISSUE TITLE
Prot Paladin Defensive skill bugged stuck at 352

### ISSUE THREAD

**Issue by cjbreeze** [SunstriderEmu/BugTracker#3625] opened 2020-06-05 17:15 UTC
My paladin has been stuck at defense skill 352/370 and i have run multiple dungeons and it has not increased since character name Palabreeze

**Comment by beraus** [comment] 2020-06-07 02:54
> This is bugged if you do not have max defense skill when you take the talent. if you are 330/350 defense skill and then take the talent you will be at 350/370 and unable to gain defense skills past 350 since the scripting thinks you are maxed. To avoid this, untalent ability, level defense skill to max, relearn talent. Common private server bug with the improved defense talents. Most likely bugged in the same manor for the warrior talent as well.

**Comment by InhumanGM** [comment] 2020-06-15 15:12
Duplicate of #3376

**Closed by InhumanGM** 2020-06-15 15:12 UTC
