### ISSUE TITLE
Warlock pet doesnt respawn if dead in battlegrounds

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3561] opened 2020-05-30 13:43 UTC
If your pet died in a battleground, you should be resurrected with your last active pet.

**Comment by Balanarr** [comment] 2020-05-30 16:34
Also when not dead and spawns, he's not full hp. Very annoying to have to constantly resummon

**Comment by InhumanGM** [comment] 2020-05-30 21:04
Duplicate of #3137

**Closed by InhumanGM** 2020-05-30 21:04 UTC
