### ISSUE TITLE
Tooga Quest

### ISSUE THREAD

**Issue by Pawnywow** [SunstriderEmu/BugTracker#2380] opened 2020-03-17 18:33 UTC
Hello,

Its about Tooga Quest -> https://classic.wowhead.com/quest=1560/toogas-quest

If you engage with her and some mob atack her.. she will start to run back to respawn point.

Please fix it.

**Comment by InhumanGM** [comment] 2020-05-14 12:42
Duplicate of #2898

**Closed by InhumanGM** 2020-05-14 12:42 UTC
Labels: bug, confirmed, quest
