### ISSUE TITLE
[Mechanics] Something is giving tank bonus threat on pull

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#732] opened 2019-03-03 01:14 UTC
**Description:**

Somehow the game is identifiying who the tanks are in the raid and giving them a burst of bonus threat on pull

**Current behaviour:**

In a raid; I pulled a mob with a 2.5k shadowbolt but that mob immedtally targeted and started running after the tank

**Expected behaviour:**

I should be on the top of the threat list given I delt 2.5k damage and the tank has done nothing; the mob should come after me not the tank

**Steps to reproduce the problem:**

CHANGEME
1. Go to high king moldar
2. Get a prot pally fully spec'd with righteous fury up to stand at the back of the room
3. Get a warlock to pull with a shadowbolt
4. Observe all the mobs instantly running after the paladin; even though it is afk and the warlock just did 2.5k damage
5. Get the thickk paladin to get naked; get it to unspec and get it to turn off righteous fury
6. Repeated the above test
7. Watch how all the mobs now chase the warlock off the pull (as expected)

Please note we performed this test twice and both times we got these results

rev 10570

https://db.excalibur.ws/?spell=20470

I'm not entirely sure what part of the tank is casuing this to happen; it could be RF: it could be that they are spec'd into prot. Palla suggested that this type of threat mechanic come into the game with WOTK so its likely been carried from there

**Comment by plutonium447** [comment] 2019-03-03 01:54
*blushes*

**Comment by Jerrythemagicdog** [comment] 2019-10-28 14:47
Attempted to reproduce, seems more like a faulty boss script in the past than a threat issue but both have been reworked extensively since then.
I've tried many combinations and failed, closing it for now.

**Closed by Jerrythemagicdog** 2019-10-28 14:47 UTC
