### ISSUE TITLE
Disenchanting an item causes mats to completely disappear if you cast a spell before looting

### ISSUE THREAD

**Issue by ahahenf** [SunstriderEmu/BugTracker#3327] opened 2020-05-11 19:13 UTC
**Describe the bug**
Whenever you disenchant an item and then cast any spell or ability the mats completely disappear

**To Reproduce**

Just tested as this happened a few times to me in the past - \
1. Disenchant an item
2. Leave the loot window open
3. Cast any spell
4. Item disappear

**Expected behavior**
Disenchanting mats are supposed to auto go into your bags or mailbox if full if this happens?

**Comment by Jerrythemagicdog** [comment] 2020-05-13 18:16
Thanks, not sure about the correct behavior here, but the ones you listed in expected behavior look like a better solution than what we have currently.

**Comment by Killko448** [comment] 2020-09-08 19:46
This bug is present since start of server...
This is just sooo frustrating to lose Large prismatic shard again just because of this bug. Now i see it was reported on 11 of May.. Usually Endless team fix such critical shit pretty fast...
And yet another -40g cause of it... alt+f4

**Comment by hufsa** [comment] 2020-10-28 16:06
Thanks, fixed with next restart.

**Closed** 2020-10-28 16:06 UTC
Labels: confirmed
