### ISSUE TITLE
Hunter pet speed is unlike retail, could be improved with Catchup mechanic

### ISSUE THREAD

**Issue by tonisjwhite** [SunstriderEmu/BugTracker#3837] opened 2020-06-30 17:42 UTC
**Describe the bug**
Hunter pets, even with the 30% outside speed, are still slower than their masters.  When in AV for instance, the hunter pet will lag behind across the start > field of strife > IBT for instance, and be there ~15s later than the hunter.

**To Reproduce**
Have a 70 hunter with the same level pet.  Any talent mixture/skill allotment for the pet.  Run a very far distance (AV starting cave to a tower/bunker).  The pet will lag behind ~15s.

Any pet.

**Expected behavior**
The pet should run alongside the hunter, and if lagging behind, the pet's speed should increase to 280% (for example) until it has caught up to the hunter, then reduce to the hunter's speed.

**Screenshots/videos**
Can provide a video, I didn't stream/record this.

**Additional context**
I have observed that warlock pets have the same behavior.

**Comment by penetrator1** [comment] 2020-07-05 14:22
I'm fresh on the server and this bug is so annoying.Mob switches aggro runs to attack me and the pet can't even catch him to taunt.I wonder how does this work in  pvp?If pet can't catch up with a player?Should be fixed asap!

**Comment by beraus** [comment] 2020-07-12 03:18
https://github.com/SunstriderEmu/BugTracker/issues/2764

**Comment by kelno** [comment] 2021-04-13 11:42
There is a catchup mechanic but it didn't work in AV sometimes because of the archers keeping players/pets in combat. I made a change since then, this should be better now.
(10 march) https://github.com/kelno/sunstrider/commit/41da60dcf618689c59655580f5730bd0cc753bfb

**Closed by kelno** 2021-04-13 11:42 UTC
Labels: pets

**Comment by deusduce2** [comment] 2021-04-28 23:27
Verified that the "catch-up" mechanic is not working. I have started a new character, tamed a pet, and tested this while running (without speed boosts) approximately 100yds. The pet steadily lost ground and was only "catching up" a minor a mount, but losing more ground than it gained. Estimated distances 20, 40, 60, and 80 yds it would fall further behind.

![WoWScrnShot_042821_161518](https://user-images.githubusercontent.com/83378039/116484751-9b303a80-a83e-11eb-8c7f-f29822cf6c04.jpg)
![WoWScrnShot_042821_161523](https://user-images.githubusercontent.com/83378039/116484753-9cf9fe00-a83e-11eb-92b5-38413000a13b.jpg)
![WoWScrnShot_042821_161534](https://user-images.githubusercontent.com/83378039/116484755-9d929480-a83e-11eb-88ea-3c2b50e1016a.jpg)
![WoWScrnShot_042821_161542](https://user-images.githubusercontent.com/83378039/116484756-9e2b2b00-a83e-11eb-8f45-76cbd30f3f4b.jpg)
![WoWScrnShot_042821_161546](https://user-images.githubusercontent.com/83378039/116484759-9ec3c180-a83e-11eb-909e-fbc0676318cb.jpg)
![WoWScrnShot_042821_161553](https://user-images.githubusercontent.com/83378039/116484760-9f5c5800-a83e-11eb-8db4-aea4e60ca447.jpg)

**Comment by kelno** [comment] 2021-04-29 17:03
Thanks for all the details. I can't get this to fail in the same way, is this a regular pet and not one from the taming quests?
I'm trying to see what could be happening in this case.

**Comment by deusduce2** [comment] 2021-04-30 05:18
This seems to happen for all regular pets. The "tame quest" specific pets just stand in place until abandoned or the timer runs out. I will say the existing catch up mechanic works to a point. After several more hours of running around and questing I've noticed the pets have a more difficult time with elevation changes (even ramps or slight grades, especially with cliffs) and objects (trees, rocks, posts, etc) between the character and pet. The catch up mechanic will catch them up to about 10m behind the character, but no closer. With just running from point A to B this is a minor inconvenience at worst, but when killing mobs who are a bit more spread out this forces the character to wait for the pet to fully catch up before attacking the next mob.

You're doing a great job tackling these issues, I'm sure you'll find the bug somewhere. Is it maybe just a matter of catch up distance or speed of the pet?

**Comment by kelno** [comment] 2021-05-01 12:45
I've been trying to use your character to reproduce the issue, here is the furthest I can get him to be:

![image](https://user-images.githubusercontent.com/3866946/116782853-d1162e80-aa8b-11eb-9362-3c65fe72cb8e.png)

He should a be a little closer indeeed, is that the issue you're reporting?

**Comment by kelno** [comment] 2021-05-01 12:47
Also, are you aware you're playing on the old realm? If you're starting to play here I would suggest playing on the new realm Windrunner. (I can move your character there if you'd like to.)

**Comment by deusduce2** [comment] 2021-05-01 16:07
That is still a pretty significant distance and causes me to have to wait for my pet to move up before it can be useful for anything.

Also, I believe Windrunner was flagged as a PvP server wasn't it? I can't stand world pvp due to all the ganking and griefing. I started on a pvp server many years ago and never got past 50 because of camping and insanely difficult grinds due to always being flagged for pvp.

If Windrunner isn't a pvp server, sure you can move me, but if it is I'd rather stay where I'm at.

Thanks for all your help!
