### ISSUE TITLE
Sanctified Seals Not Working

### ISSUE THREAD

**Issue by brapper69** [SunstriderEmu/BugTracker#1971] opened 2020-03-01 06:15 UTC
Paladin seals still dispellable with the sanctified seals talent on the ret tree

**Comment by SUN-Leekie** [comment] 2020-03-05 00:07
Cannot reproduce.
We have an automated test passing and I even tried to do it manually.

**Comment by DollpartsFTP** [comment] 2020-03-05 01:00
I posted this on discord earlier after having my seal spam dispelled by a ganking shadow priest.

The talent should make you immune to seal being dispelled, currently it does nothing.

**Comment by SUN-Leekie** [comment] 2020-03-05 12:42
Can you try the following and report me the results:
- Having it dispelled alone
- Having it dispelled with multiple other buffs

**Comment by DollpartsFTP** [comment] 2020-03-05 12:47
Dispellable both ways, with other buffs, and without.

**Comment by SUN-Leekie** [comment] 2020-03-07 05:10
Closing until further proofs are provided.

**Closed by SUN-Leekie** 2020-03-07 05:10 UTC
Labels: question

**Comment by GigilPiq** [comment] 2020-03-07 22:56
No need to close, it does bug and the seals gets dispelled. Can confirm this happened multiple times.

**Comment by GigilPiq** [comment] 2020-03-07 23:03
There is your proof, just duel'd another pal, Used Seal of the Crusader and Judge'd it, then got him to dispell.

Here's combat log : 
![image](https://user-images.githubusercontent.com/59665141/76153714-09142280-60d0-11ea-823f-a961a419d1dd.png)

Here's the talent :

![image](https://user-images.githubusercontent.com/59665141/76153723-22b56a00-60d0-11ea-9bcd-a670a7beb988.png)

**Comment by SUN-Leekie** [comment] 2020-03-08 03:56
Your proof is a *judgement* dispel not a *seal*.

**Comment by GigilPiq** [comment] 2020-03-08 20:23
> Your proof is a _judgement_ dispel not a _seal_.

You are joking, right ?

**Comment by blblblaz** [comment] 2020-03-08 20:46
what this talent does is make your Seals "undispellable" if you have 3 points in it, Judgments are not Seals, the debuff you put on your enemy has nothing to do with this talent

**Comment by GigilPiq** [comment] 2020-03-08 20:57
> what this talent does is make your Seals "undispellable" if you have 3 points in it, Judgments are not Seals, the debuff you put on your enemy has nothing to do with this talent

What the f are you talking about ? Judging SoC applies the debuff *Judgement of the Crusader*.

**Comment by blblblaz** [comment] 2020-03-08 21:01
and Judgement of the Crusader is not Seal of the Crusader, this talent relates to the buff that you have before using Judgement

**Comment by GigilPiq** [comment] 2020-03-08 21:01
> and Judgement of the Crusader is not Seal of the Crusader, this talent relates to the buff that you have before using Judgement

Yes you are right, I went full retard on this one. Sorry.
I don't know why I was sure the Judgement debuff should not be able to be dispelled.

**Comment by blblblaz** [comment] 2020-03-08 21:03
no worries, most of the time the wording on these things is weird so it's easy to get confused by just reading it in a tooltip

**Comment by GigilPiq** [comment] 2020-03-08 21:29
I swear I could remember my SoC not being able to be dispelled. I am totally wrong here ?
