### ISSUE TITLE
Focused Assault WSG

### ISSUE THREAD

**Issue by Neo0760** [SunstriderEmu/BugTracker#4207] opened 2020-09-13 15:22 UTC
Paolly - Night Elf Druid (shit person) was somehow removing the Focused Assault debuff (for carrying flag for too long in WSG), he did so by decursing while in cat form (casting faerie fire emote), plus had a 100% hit chance on me while I had Evasion(50% dodge) + Ghostly Strike (15% dodge) + 29% dodge from stats = 94% dodge overall

I am reporting a bug and an abusing shit player @Simon-GM @InhumanGM 
![WoWScrnShot_091320_163901](https://user-images.githubusercontent.com/64336777/93021741-bd918280-f5e4-11ea-88ed-97540d449f05.jpg)
![WoWScrnShot_091320_163904](https://user-images.githubusercontent.com/64336777/93021747-cbdf9e80-f5e4-11ea-9188-2ba1a8d77474.jpg)
![WoWScrnShot_091320_164500](https://user-images.githubusercontent.com/64336777/93021804-224cdd00-f5e5-11ea-979a-401d58644db8.jpg)
![WoWScrnShot_091320_164456](https://user-images.githubusercontent.com/64336777/93021824-4c9e9a80-f5e5-11ea-96a5-c329cf4fac0a.jpg)

**Comment by Jerrythemagicdog** [comment] 2020-09-13 17:31
Is there any chance this is your addon displaying only a few debuffs and buffs?
I can't reproduce locally.

**Comment by Jerrythemagicdog** [comment] 2020-09-13 19:15
Fixed with next update, thanks.

**Closed by Jerrythemagicdog** 2020-09-13 19:15 UTC

**Comment by Neo0760** [comment] 2020-09-14 00:05
what about the player? Is he just gonna go unpunished for abusing this and frustrating 10 other players?
There needs to be an investigation on this player considering the other issue not missing any hits on me with 94% dodge active, and last I checked his character on armory he has 0 expertise!
