### ISSUE TITLE
Can't use portal if mage already ported in it

### ISSUE THREAD

**Issue by b0rnless** [SunstriderEmu/BugTracker#2097] opened 2020-03-04 21:39 UTC
**Describe the bug**

When you cast Portal: Theramore, your party members aren't able to click on it. 

**To Reproduce**
1. Be Alliance
2. Cast Portal: Theramore
3. See if party members are able to teleport to Theramore with it. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**

Your party members should be able to teleport to Theramore by clicking on the portal.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by kelno** [comment] 2020-03-05 00:20
Possible bug:
I hear the portal doesn't work anymore if the mage already ported in it

**Comment by kelno** [comment] 2020-03-21 09:00
Should be fixed now

**Comment by hufsa** [comment] 2020-03-21 17:35
To dev: the problem is the GetOwner() call only looking for owner in that map.

**Comment by artieau** [comment] 2020-09-07 11:17
Tested and works fine now

**Closed by artieau** 2020-09-07 11:17 UTC
Labels: confirmed, core, testfix
