### ISSUE TITLE
Disconnect while leaving fly mount/flight form

### ISSUE THREAD

**Issue by Kotchimotchi** [SunstriderEmu/BugTracker#2892] opened 2020-04-10 22:16 UTC
**Describe the bug**
50% of the time when you demount , shapeshift out of flight form close to a gas cloud you get disconnected.

**To Reproduce**
Fly down towards a gas cloud with 280% mount -> unmount -> get disconnected.

**Expected behavior**
You should not get disconnected.

**Comment by Godmatik** [comment] 2020-04-10 22:22
Confirmed.

**Comment by lukas155** [comment] 2020-04-11 03:43
I think this is a sloppily applied anti-cheat mechanism. For a brief second after dismounting you are travelling unmounted at a speed not normally possible, so the anti cheat assumes possible speedhack and DCs.

**Comment by kelno** [comment] 2020-04-11 11:05
I made a related fix yesterday, it might have fixed this. Is this still happening since last restart? (This morning)

**Comment by Stolemyname1** [comment] 2020-04-11 13:08
This just happened to be about 30 seconds ago, so yes still happening.

**Comment by LSD7** [comment] 2020-04-11 15:15
yep, same for me

**Comment by coder3838** [comment] 2020-04-11 20:59
It happens less often than yesterday, still happens though.

On mining the times I've notice this happen was when landing on top of the node and getting that small pushback some people mention above it disconects instead of pushing back, only when landing on top of a node.

Had this happen while herbing with druid form for this nothing specific was done, just landing on the node and getting dc as i went out of fly form.

Still is better than yesterday when it happen way too often,

**Comment by kelno** [comment] 2020-04-12 09:17
Thanks we were able to reproduce it, we're looking into it now.

**Comment by mayday2013** [comment] 2020-04-13 06:55
still getting dced 2-3 times in a row, once in 15 min I die due to fall damage. is it anticheat system?

**Comment by kelno** [comment] 2020-04-13 11:09
I don't think fall damage has been reported before, it might be related but it looks like another issue.
The anticheat doesn't kill you ever. 
Can you give some details on the fall damage one?

**Comment by Godmatik** [comment] 2020-04-13 14:49
The fall damage thing I have experienced once before, but wasn't able to reproduce. I think I was coming in fast with an epic flyer and landed on a slope/incline.

**Comment by mayday2013** [comment] 2020-04-14 06:55
I don't know how to reproduce it, but it happens when you fly towards the ground and dismount at 10y height for a node or gas cloud, etc.

You expect 0-200 damage from hitting the ground, but it kills you.

I have a yt vid linked in the post, and it always looks like it.

Have dismounted 20-30 times today and not dcs. Seems you did something - thanks!

**Comment by kelno** [comment] 2020-04-14 13:48
The disconnect bug should still be present, I just made a fix now, applied with next restart

**Closed** 2020-04-17 09:16 UTC
Labels: confirmed, core, testfix
