### ISSUE TITLE
Cant put item with full charges into auction house

### ISSUE THREAD

**Issue by zecke345** [SunstriderEmu/BugTracker#3812] opened 2020-06-26 22:29 UTC
i crafted "thick felsteel necklace" (jewelcraft), it has 10 charges.
Can't put it into auction house. It says: i cant put the item with used charges into AH, which is ridicolous.

it has the FULL 10 charges. i never used it. i made it and sent it to a low lvl bankchar, which cant even accidently use the charges.
Also its BOE, and i never equipped it ofc, as it'd be soulbound then.

Cant imagine that this will ever fixed...  now i am sitting on those 2 items and cant sell it.

**Comment by InhumanGM** [comment] 2020-06-27 18:13
Duplicate of #3475

**Closed by InhumanGM** 2020-06-27 18:13 UTC
