### ISSUE TITLE
Greatfather Aldrimus NPC is nowhere to be found

### ISSUE THREAD

**Issue by Pecka69** [SunstriderEmu/BugTracker#2785] opened 2020-04-06 17:31 UTC
**Describe the bug**
Greatfather Aldrimus is a ghost NPC quest giver, near Auchenai Crypts. He gives alliance quest "Everything will be alright". Few weeks i got quest from him, and everything was fine. I completed it recently, but cannot finish the quest because greatfather Aldrimus is invisibble to me somehow, other players reported that they can clearly see him.
![Untitled](https://user-images.githubusercontent.com/50052109/78587450-a2586500-7845-11ea-9ffc-43744e973e2e.png)

**Comment by Ironjudgment** [comment] 2020-04-07 10:01
I have the same issue :] This NPC requires a pre-quest to be able to see the NPC but the problem is I've already completed that quest, taken the quest for AC but can't turn it in since I can't see the NPC now.
![image](https://user-images.githubusercontent.com/33090790/78656341-269afe80-78bf-11ea-8485-6972764f2027.png)

**Comment by Jerrythemagicdog** [comment] 2020-04-09 04:39
Have you completed the quest chain in Nagrand with Nithrin the Learned (19844) one of which is Vision of the Dead (10252)? Finishing that quest allows you to see those NPCs.

**Comment by Pecka69** [comment] 2020-04-09 21:55
yes, as you can see in the image above i have already got the quest from Greatfather Aldrimus, which i was able to see before. I completed the quest, but cannot turn it in, becouse i cannot see this npc now

**Comment by artieau** [comment] 2020-04-10 02:46
I have seen 3 or 4 player with this same issue now @Jerrythemagicdog

**Comment by Mojigam** [comment] 2020-04-14 17:41
Same problem, i completed all the quest chain and even finished the last quest "Everything will be alright" and can't see the npc

**Comment by Hustler495** [comment] 2020-04-18 15:46
I too completed the quest - Everything will be alright. Exited from insta and do not see the NPC to complete the quest, another player completed the quest. Now I am at the place of the quest

**Comment by Sheikthecatman** [comment] 2020-05-04 16:22
Fixed in [32948668ce04c51a61d62bea890955d1e43dec77](https://github.com/kelno/sunstrider-scripts/commit/32948668ce04c51a61d62bea890955d1e43dec77)

[Vision of the Dead](https://www.wowhead.com/quest=10252/vision-of-the-dead) needs to be completed in order to see the spirits.

**Closed by Sheikthecatman** 2020-05-04 16:22 UTC
Labels: question
