### ISSUE TITLE
Ban for no reason

### ISSUE THREAD

**Issue by damnutys** [SunstriderEmu/BugTracker#3426] opened 2020-05-18 13:19 UTC
In-game name: Ethrall

Describe the bug
I'll open the game I'm flying to the terokar, I picked up 10 flowers and ban for botting. 10min ago
You can do something, please do not use any software except multibox and multibox is allowed according to the rules.

**Expected behavior**
Unban and explanation will be good.

**Comment by InhumanGM** [comment] 2020-05-18 15:06
Closing this issue as it is not a bug. You can reach out to Support Manager Simon (Endless Simon#1337) on Discord for ban appeals.

**Closed by InhumanGM** 2020-05-18 15:06 UTC
