### ISSUE TITLE
 [Warrior][Spells][Threat] Devastate

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#3162] opened 2020-04-28 08:04 UTC
Devastate currently is bugged in a few ways.  It does not apply sunder armor spell threat and only applies devastate threat (sunder armor debuff is applied to target, threat from sunder armor is missing).

All testing was done with macros to prevent auto attacks.  All proc items removed.  Shield removed to prevent Shield Specialization rage generation causing threat.  Threat meter cleared via commander before each screenshot.

Threat formula for devastate should be something like:
Devastate (damage) +106 (base threat) + [14 * Sunder Count] + Sunder Armor Threat (Rank 6 sunder armor is 300 threat)
Current formula being used is not including the Sunder Armor Threat.

![image](https://user-images.githubusercontent.com/62405847/80460859-41bec400-88e9-11ea-9783-de2ee5374679.png)
Devastate done in defensive stance with defiance talent.  Devastate dealt 107 damage.  Threat should be:
(107 + 106 + 14 + 300) *1.3 (defense stance) * 1.15 (defiance)  = 788
Actual Threat: (107 + 106 + 14) *1.3 (defense stance) * 1.15 (defiance)  = 339

![image](https://user-images.githubusercontent.com/62405847/80461626-68c9c580-88ea-11ea-8079-d74a1cf5e935.png)
A normal sunder armor only. 
300 *1.3  * 1.15  = 448

https://db.endless.gg/?spell=30022
https://db.endless.gg/?spell=25225

Devastate should always be applying highest learned sunder armor spell rank threat on attack.  Currently Devastate is doing less threat than a normal Sunder Armor.

**Comment by mechanicsTBC** [comment] 2020-04-28 09:06
https://db.endless.gg/?spell=30022
"Sunder the target's armor causing the Sunder Armor effect.  In addition, causes 50% of weapon damage **_plus 35 for each application of Sunder Armor on the target._**  The Sunder Armor effect can stack up to 5 times."

test done on https://db.endless.gg/?npc=18476 npc.  armor value not shown on database.

![image](https://user-images.githubusercontent.com/62405847/80467942-691a8e80-88f3-11ea-8ddc-fd3e632c5009.png)
[Devastate] hits Timber Worg for 110 Physical.  this is the first devastate

![image](https://user-images.githubusercontent.com/62405847/80468338-e6460380-88f3-11ea-917f-6b9890282e6e.png)
[Devastate] hits Timber Worg for 236 Physical.  devastate done with 5 sunders on target.

While there is obviously some RNG with weapon damage range it's obvious something with devastate dealing additional damage per sunder armor stacks isn't working.
110 damage with 0 sunders applied.  110 + 35 * 5 = 285 before accounting for the 2600 armor reduction from the 5 sunders applied.  something is wrong with the additional 35 damage dealt per sunder armor debuff.

**Comment by mechanicsTBC** [comment] 2020-04-28 09:27
Also, when this is fixed and Devastate is applying sunder armor threat, it's important to make it interact properly with improved expose armor.  Devastate should still be able to be used while improved expose armor is on the target ("a more powerful spell is already active" should not prevent use of devastate).  

Devastates threat formula is still the same as before:
Devastate (damage) +106 (base threat) + [14 * Sunder Count] + Sunder Armor Threat (Rank 6 sunder armor is 300 threat)

Because improved expose armor is a more powerful spell, sunder armor DEBUFF will not be applied to boss.  Devastate will not gain the additional 35 * sunder debuff damage.  Devastate will not gain the addition 14 * sunder count threat.  Sunder armor threat will not be applied and the debuff will not. 

It is important that devastate deals the threat from sunder armor even if not applying sunder armor debuff or devastate will deal 250-350 threat max when improved expose armor is up.

**Comment by frastsytt** [comment] 2020-04-28 11:55
Right on brother, ur doing gods work.

**Comment by kelno** [comment] 2020-04-28 12:52
Nice thanks for all the research work.
I didn't check yet but there is a critical issue with the way this is tested:
The threat meter addons only do guess work and have no idea about the real values the server uses. Thus the value you see might not be the server one.

I've added you the command ".debug threat" on this character, you can use it to see the exact values the server currently has on a target vs you.

**Comment by Edmondclassic** [comment] 2020-04-28 12:58
I am getting the same results as Thunar using Omen, only the Devastate threat is applied but not the Sunder Armor part

**Comment by mechanicsTBC** [comment] 2020-04-28 22:25
Sunder Armor
![image](https://user-images.githubusercontent.com/62405847/80540481-48d3e980-895e-11ea-8ecd-27b7f1c6f104.png)
Sunder armor working properly
301 * 1.3 * 1.15 = 449.995

Devastate
![image](https://user-images.githubusercontent.com/62405847/80539786-f5ad6700-895c-11ea-8f6f-80fd479dc98f.png)
So it seems the addon is the major thing broken here.  Devastate is applying sunder armor threat.  Also the order of the additional threat from having sunder armor stacks is proper using the debug command.  [14 * Sunder Count] this part should not be counted on the first devastate as devastate hits first before the sunder armor debuff is applied.  That is working properly using the debug command, just mentioning it as it was being applied incorrectly to devastate on the threat meter addon.

Devastate (damage) +106 (base threat) + [14 * Sunder Count] + Sunder Armor Threat (Rank 6 sunder armor is 301 threat) * 1.3 (defense stance) * 1.15 (defiance)

Should be:
110 + 106 + 0 + 301 * 1.3 * 1.15 =  772.915
Threat shown by debug command = 690.689

https://db.endless.gg/?spell=30022
"Sunder the target's armor causing the Sunder Armor effect.  **_In addition, causes 50% of weapon damage plus 35_** for each application of Sunder Armor on the target.  The Sunder Armor effect can stack up to 5 times."

It seems the damage modifier of Devastate is being used for the threat modifier of devastate.  The actual damage that devastate deals is having its threat reduced by 50%.  That is the only way I can see to get the same threat readout as shown in screenshot above.

So looking at screenshot above, if we multiply devastate damage by .5 we get the threat shown from debug:

55 + 106 + 0 + 301 * 1.3 * 1.15 =  690.69
Threat shown by debug = 690.689

So the 50% weapon damage modifier is also incorrectly being applied to the threat generated by the damage portion only of devastate and reducing it by 50%.  Both the base threat of devastate and sunder armor are not effected by this.  I will test soon devastates at each sunder armor stack.

**Comment by mechanicsTBC** [comment] 2020-04-29 01:49
1st Devastate
![WoWScrnShot_042820_152121](https://user-images.githubusercontent.com/62405847/80548341-91e06980-896f-11ea-8e7e-7464399d780d.jpg)

Same issue above with devastates damage portion having its threat reduced by the 50% modifier
61.5 + 106 + 0 + 301 * 1.3 * 1.15 = 700.4075 threat

2nd Devastate 
![WoWScrnShot_042820_152130](https://user-images.githubusercontent.com/62405847/80548655-44b0c780-8970-11ea-8ad9-4a49b93375c4.jpg)
Firstly need to subtract threat from previous sunders to see how much threat this one did specifically.
1406.047 (Total threat)  - 700.4075 (threat from all previous sunders)  = 705.639 threat 
Should be:
58 + 106 + 14 + 301 * 1.3 * 1.15 = 716.105
Actual:
58 + 106 + 7 + 301 * 1.3 * 1.15 = 705.64
The [14 * Sunder Count] additional threat of devastate is also currently being reduced incorrectly by the 50% damage modifier of devastate.  

Will not do calculations for sunders 3 4 5 as they all follow the same pattern, but will post screenshots for proof.

3rd Devastate
![Sunder 3](https://user-images.githubusercontent.com/62405847/80549672-ba1d9780-8972-11ea-8c50-d6b99bf3707d.jpg)

4th Devastate 
![Sunder 4](https://user-images.githubusercontent.com/62405847/80549692-c3a6ff80-8972-11ea-9570-d07026a6859d.jpg)

5th Devastate
![Sunder 5](https://user-images.githubusercontent.com/62405847/80549702-cd306780-8972-11ea-9c64-aae383b8c199.jpg)

Any devastates done on a target with 5 sunder armor debuffs are no longer applying sunder armor threat (only refreshing sunder armor debuff duration).

6th Devastate
![Sunder 6](https://user-images.githubusercontent.com/62405847/80550180-25b43480-8974-11ea-9e36-ef93e53ea406.jpg)
4165.816895 (Total threat)  - 3759.177002 (threat from all previous sunders)  = 406.639893 threat
Sunder armor threat is not being applied when sunder armor debuff is at 5 stacks. 
131 + 106 + 35 * 1.3 * 1.15 = 406.64

While it is stated in http://web.archive.org/web/20080811093508/http://elitistjerks.com/f31/t18771-protection_warrior_guide/ (which is where I assume where this was taken from) that the sunder armor threat should only be applied when increasing the stacks of sunder armor, this is not correct (maybe it was at the time of the post, or it was a bug, an addon bug the same as I had above, the player could also just have been wrong).  

No matter the state of the target, devastate should always be following the same pattern:
combat roll (hit,miss,dodge,parry,block etc) > weapon damage range roll * 0.5 > [35 * Sunder Count] additional damage > devastate base threat > [14 * Sunder Count] additional threat > Sunder Armor application.  Whether or not the target is gaining a new stack of sunder armor does not change this pattern.  Sunder armor threat is always applied by devastate even if target already has 5 stacks. 

That protection warr guide from elitist jerks is the only post I can find anywhere stating devastate should only apply sunder armor threat when increasing the stack amount. 
Use search function for devastate for most of these:
https://wowwiki.fandom.com/wiki/Patch_2.3.0
https://wowwiki.fandom.com/wiki/Devastate?oldid=1575528
https://www.wowhead.com/forums&topic=7014/devastate
https://vanilla-wow.fandom.com/wiki/Sunder_Armor
"The threat effect of Sunder Armor continues to occur even after the fifth stacked Sunder Armor debuff, so a tank can continue to reapply it after five sunders have stacked – it will still generate the same amount of threat, but will not stack past five debuffs."

All posts indicate that devastate is basically just sunder armor with extra threat and damage.  Sunder armor applies threat when at 5 sunder stacks still.  There is no reason that devastate would not do the same.  The elitist jerks post is not correct devastate behavior.

**Comment by mechanicsTBC** [comment] 2020-04-29 02:22
So a summary of whats bugged about devastate to be used for confirmation/testing:

1.  Devastate threat is not being shown properly on some threat addons.  Not sure if this is some that can be fixed server side or is addon specific.


2. Devastate deals 50% weapon damage.  That 50% weapon damage modifier is being applied to the threat devastate deals in multiple ways
	- Threat gained from devastate damage is being reduced by 50%
	- [14 * Sunder Count] additional threat gained by sunder armor count is being reduced by 50%


3. Devastate is suppose to deal "plus 35 for each application of Sunder Armor on the target."  It is currently doing 1 of these 3 bugged things (very hard to test precisely with weapon that has damage range, but still obvious that something is bugged in above screenshots.  Give yourself a custom 1-handed weapon with 1-1 damage range and test to see which version it is):
	- 35 additional damage per each application of sunder armor not working at all
	- 35 additional damage per each application of sunder armor damage being reduced by 50%
	- 35 additional damage per each application of sunder armor threat being reduced by 50%
	-  Devastate should use formula along these lines (with 50% damage modifier only applying to base weapon damage, not the additional damage and not to threat:
(weapon_damage) * 0.5 + [35 * Sunder Count] = damage

4. Devastate is not dealing Sunder Armor threat when Sunder Armor debuff is at max stacks.
	- Devastate always applies a Sunder Armor which should always deal threat regardless of stacks. 


5. Devastate threat with Expose Armor (havent tested yet but assume this is how it works, will update when i do)
	- Devastate not applying Sunder Armor threat when Expose Armor is on boss.

**Comment by Bugadin** [comment] 2020-05-04 10:54
ZZZ.....

**Comment by kelno** [comment] 2020-05-12 11:31
Thanks for the clean and specific answer, that will help a lot

**Comment by kelno** [comment] 2020-05-13 16:18
1. No way to fix that really, addons just do their own thing there using combat log and guessing.
2. Should be fixed with next server update.
3. "35 additional damage per each application of sunder armor threat being reduced by 50%" is the one that was happening, same issue as 2.
4. Seems to be intended in the code. I'm going to remove that limitation and make it apply even on 5 stacks, since you're providing some source for it. It makes more sense anyway.
5. I can confirm this is how it works right now (sunder threat not applied). The reason for it is that the spell fails to cast (even before applying) because target has a more powerful aura. So the proof I would need here is: Can you actually *cast* (= lose rage, make threat, but no debuff applied) a Sunder Armor on a target with improved expose armor? Currently it just returns a "more powerful aura" message but I'd like proof this is incorrect before doing any changes to that.

**Comment by mechanicsTBC** [comment] 2020-05-14 17:20
4. I think it was just taken from that elitist jerks post that says it shouldn't generate threat at max stacks, but all other sources say it should.

5. Yeah I was rather unsure about this one as I haven't really tested it much in the past.  The way you're saying makes sense.  Browsed around shortly and couldn't find anything saying sunder should generate threat when expose is up.  So as long as devastate is dealing threat based on its damage while expose armor is up, that one seems to be working properly atm.

**Comment by kelno** [comment] 2020-05-15 09:23
Alright then I'll close for now, I'll leave you the command in case you want to do further tests. If there are still issues with this you can answer here or open another ticket to keep it clean.

**Closed by kelno** 2020-05-15 09:23 UTC
Labels: confirmed, core, spells, testfix
