### ISSUE TITLE
Mobs drop combat in Black Morass

### ISSUE THREAD

**Issue by djobf** [SunstriderEmu/BugTracker#3531] opened 2020-05-28 13:37 UTC
Trash non-elite mobs drop combat in both BM normal and heroic, this wasn't the case before and not the case in retail either. Resetting the instance and clearing the cache change nothing to the issue.

**Comment by SabreValkyrn** [comment] 2020-05-28 23:36
Sounds like a duplicate of #3514.

**Closed** 2020-05-28 23:38 UTC
