### ISSUE TITLE
[NPC] Arcatraz - Drakanoid (final boss add) too strong

### ISSUE THREAD

**Issue by Paralol** [SunstriderEmu/BugTracker#1139] opened 2019-04-19 06:17 UTC
**Description:**

List of issues

**Current behaviour:**

1. Respawns are very fast. 3 defenders in the 1st room. Pack in 2nd room. Dogs and eyeball guys near 1st boss.
2. 2 Sentinel's after 2nd/3rd boss respawn fast and respawn on 100% health instead of 40%
3. Drakanoid as part of end boss event damage done by blast wave is 1 shotting people even on normal difficulty. Uptime on mortal strike is close to 100%

**Expected behaviour:**

None of the above.

**Steps to reproduce the problem:**

1. Run instance
2. Get dumpstered 

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/4516769/56409884-620f7800-62be-11e9-85d1-02104fd80de2.png)

**Comment by giveusmezpls** [comment] 2019-04-19 07:49
Hi Para,
Do you know the SPELLID and NPCID this will save the Developers some time.
If you are not sure how to find them out i can assist.
Regards,
Jaysue.

**Comment by kelno** [comment] 2019-04-19 13:01
Respawn times should be fixed with 11031

**Comment by artieau** [comment] 2019-04-25 01:39
Spell ID 39038

**Comment by Jerrythemagicdog** [comment] 2019-10-26 14:16
The Blast Wave spell (39038) does around 3.5k - 4k damage. It's the correct spell that the NPC has by design.
The other issues were fixed previously.

**Closed by Jerrythemagicdog** 2019-10-26 14:16 UTC
Labels: confirmed
