### ISSUE TITLE
Doomlord Kazzak and lvl 1 griefing...

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3018] opened 2020-04-17 20:19 UTC
Please make Doomlord Kazzak teleport to hearthstone any player under level 58 that gets within a certain agro range (think Doomwalker death aura) or that is "killed" by his AOE  (teleport them rather than letting him proc heal off their death).

using same faction level 1 toons to grief/stop Kazzak attempts by getting killed healing the boss ... may be blizzlike... but is just abusive and not legitimate competition.

**Comment by michaelkittrell** [comment] 2020-04-17 20:33
might also want to make people who are freshly ressed also be teleported away if hit by his aoe.  maybe use the honorless target timer.

ressing at the boss feet with half health again... might be blizzlike but isn't legitimate competition.

**Comment by Sensoger** [comment] 2020-04-17 21:53
hahahahaha ally crying

**Comment by NeonicSupersonic** [comment] 2020-04-17 22:13
Maybe make his spawn with 1 hp aswell so you can safely loot him without participating in any pvp?

**Comment by michaelkittrell** [comment] 2020-04-18 00:13
im horde you ass hat and my guild was amongst those griefing with level 1 same faction toons.  i think its retarded, but as long as it exists, you better believe im going to use it.  fukin nooblords

**Comment by NeonicSupersonic** [comment] 2020-04-18 00:59
Seem like you are very upset about not being able to kill any world bosses ^)

**Comment by michaelkittrell** [comment] 2020-04-18 18:19
Our shaman's legs of benediction would seem to indicate otherwise.   

do you ever get tired of being wrong?  or is it so constant that you think its normal?

**Comment by Sensoger** [comment] 2020-04-18 18:20
lol still crying?

**Comment by michaelkittrell** [comment] 2020-04-18 18:21
still contributing high value content and educated opinions?

**Comment by artieau** [comment] 2020-04-20 00:39
Not a bug, closing.

**Closed by artieau** 2020-04-20 00:39 UTC
