### ISSUE TITLE
[Battered Steam Tonk Controller] Gamebreaking behaviour

### ISSUE THREAD

**Issue by kevin-chowanski** [SunstriderEmu/BugTracker#3506] opened 2020-05-26 12:25 UTC
**Describe the bug**
When using the item [Battered Steam Tonk Controller] or [Steam Tonk Controller], you can use the spell that fires a shell (I think it is "2" in action bar) to AOE kick everyone, allies and ennemies. It is super broken because I tried to use it in battlegrounds and it works !
So you can (for exemple) hide somewhere in a corner or Arathi Bassin and defend a base just by spamming a button because people won't be able to take the flag.
And guess what? Ennemies can't target the toy.
I'm pretty sure you can find broken mechanic with this item in PVE too !

**To Reproduce**
Just use the item and fires some shells !

https://db.endless.gg/?item=31666 I'm using this one but I'm pretty sure that https://db.endless.gg/?item=22728 is exactly the same toy.

**Expected behavior**
I don't really know... But please don't disable this item forever because I like it :(

**Screenshots/videos**
Don't have any "proofs" but you can try yourself.. To be honest, I wasted all my charges with these experiences.

**Comment by InhumanGM** [comment] 2020-05-26 23:54
Duplicate of #2649

**Closed by InhumanGM** 2020-05-26 23:54 UTC
