### ISSUE TITLE
items get deleted if try to loot or use other item when bags are full

### ISSUE THREAD

**Issue by oldspices** [SunstriderEmu/BugTracker#2591] opened 2020-03-28 07:21 UTC
**Describe the bug**

Bags were full when disenchanting items for materials- I tried to "use" an item (an elixir, my last 1) To free up a bag space and loot the dust- but when using it the item+ mats disappeared. I also tried consuming a last food item and it also deleted item. now I Know this is a bug. 
**To Reproduce**
 fill bags and use item when disenchanting loot table is up
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

it should remain in the loot table until u clear a spot or delete the item that is being DE'd
**Screenshots/videos**

**Additional context**

rip materials

**Comment by InhumanGM** [comment] 2020-06-01 18:19
Duplicate of #3327

**Closed by InhumanGM** 2020-06-01 18:19 UTC
