### ISSUE TITLE
Horde reputation from WPL quests

### ISSUE THREAD

**Issue by redeemer497** [SunstriderEmu/BugTracker#3669] opened 2020-06-10 19:53 UTC
Not certain about all quests that give reputation to Horde, which should increase reputation with all Horde major cities, but the quests from WPL which award Argent Dawn and Horde reputation currently give no reputation for the Horde cities despite receiving the message that Horde reputation has increased by X amount.

**Comment by InhumanGM** [comment] 2020-06-15 15:10
Duplicate of #3058

**Closed by InhumanGM** 2020-06-15 15:10 UTC
