### ISSUE TITLE
Zeppelin Grom'Gol Base to UC is bugged

### ISSUE THREAD

**Issue by dammi2** [SunstriderEmu/BugTracker#3195] opened 2020-04-30 18:23 UTC
I am falling through in the middle of the ride (before the loading screen). I get on the shit it goes till the end of stranglethorn vale (north) and then I am sliding through the ship down and die.

**Comment by beraus** [comment] 2020-05-04 23:22
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/445

**Closed by beraus** 2020-05-04 23:22 UTC
