### ISSUE TITLE
Incendicite Ore

### ISSUE THREAD

**Issue by RasmusPG** [SunstriderEmu/BugTracker#2642] opened 2020-03-30 21:20 UTC
Incendicite veins are supposed to be fast spawning due to them being part of a quest, and should spawn in a cave called Thelgan Rock in the Wetlands. They don't spawn at all

**Comment by InhumanGM** [comment] 2020-05-14 12:36
Duplicate of #2548

**Closed by InhumanGM** 2020-05-14 12:36 UTC
