### ISSUE TITLE
[Paladin] Seal of Vengeance

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#3383] opened 2020-05-15 20:41 UTC
**Describe the bug**
When DoT reaches 5 stacks there is instant holy demage missing.
https://github.com/SunstriderEmu/BugTracker/issues/340
is incorrect

**To Reproduce**

1. Get 5 stacks of holy veangeance
2. Observe no additional dmg on reappliacation of dot.

**Expected behavior**
![image](https://user-images.githubusercontent.com/45561230/82094089-aefd9200-96fc-11ea-918b-6d9eea8f401f.png)
https://wowwiki.fandom.com/wiki/Patch_2.2.0

The instant holy demage at 5 stacks was added in 2.2, but tooltip reflecting the change was added in wotlk.

**Additional context**
Please revert the change, SoV is ultimate garbage right now. It might not be relevant, but warmane had it working exactly as you had, before you removed the instant holy dmg. Ofcourse its probably not supposed to do 1k in blue gear.

**Comment by Aeded** [comment] 2020-05-15 20:49
![image](https://user-images.githubusercontent.com/45561230/82094794-0f410380-96fe-11ea-95f8-17590518c158.png)
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549180 also proves there is supposed to be instant holy dmg at max stacks. However I dont know what should be the base dmg value for this.

**Comment by InhumanGM** [comment] 2020-05-21 11:34
Duplicate of #3153

**Closed by InhumanGM** 2020-05-21 11:34 UTC
Labels: spells
