### ISSUE TITLE
The Quest "Kindness" in ShadowmoonValley is bugged

### ISSUE THREAD

**Issue by Lykahpala** [SunstriderEmu/BugTracker#3486] opened 2020-05-24 14:26 UTC
**Describe the bug**
When laying down the Carcass from the Rockflayer, none of the Netherwing comes down to eat it and fulfill the quest requirement. 

Quest: https://www.wowhead.com/quest=10804/kindness

**Expected behavior**

Obviously that the Netherwing drakes come down , eat the carcass and are "saved" like intended

Due to the fact, that it is a mandatory pre dungeon/raid bis Series of Quests, it's really mandatory that it works correctly. 

Thanks for the effort

**Comment by beraus** [comment] 2020-05-24 16:54
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2549

**Closed by beraus** 2020-05-24 16:54 UTC
