### ISSUE TITLE
Can't fill my Etched Phial with Moonwell Water

### ISSUE THREAD

**Issue by Djarvin** [SunstriderEmu/BugTracker#3953] opened 2020-07-16 21:11 UTC
**Describe the bug**
Went to the requested location
Tried to do said quest
Game doesnt respond to required action
![image](https://user-images.githubusercontent.com/68401828/87722966-a4a05880-c77e-11ea-914c-58a778fb8182.png)

**To Reproduce**
Not quite sure how to reproduce it, but I would like for it to get fixed

Item: https://wowhead.com?item= Etched Phial
Quest: https://wowhead.com?quest= The Sacred Flame
Spell: https://wowhead.com?spell=

**Expected behavior**

Expected to fill the Etched Phial with Moonwell Water

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/68401828/87723186-0b257680-c77f-11ea-8f6f-341406e0fd79.png)

**Additional context**

**Comment by Jerrythemagicdog** [comment] 2020-09-06 12:03
Can't reproduce, probably fixed in some update and issue wasn't closed.
Thanks for the issue.

**Closed by Jerrythemagicdog** 2020-09-06 12:03 UTC
