### ISSUE TITLE
[#247] [Quest] Totem of Yor

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#524] opened 2019-02-14 21:50 UTC
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silumor](https://github.com/silumor)**
_Sunday Feb 03, 2019 at 00:19 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/247_

----

quest=9541

Tell us what happens: You receive a buff called Embrace of the Serpent spell=30430
And told to swim to the quest objective npc=17363
If this buff fades while under water, you are killed instantly 

**Expected behaviour:**

When this buff fades, it should bring up the "Breath" bar, this should slowly drop as you hold your breath

**Steps to reproduce the problem:**

1. Step 1 Get quest
2. Step 2 Swim to quest objective
3. Step 3 Complete quest, which in turn removes the buff, you die instantly.

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

Sunstrider Rev. 10357 (a9a5f35b2353) 2019-02-02 00:25:39 -0500 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment] 2019-10-30 01:15
Thanks!
Tested now, unable to reproduce. I have a suspicion about what might have been causing it, and it was fixed in the past.

**Closed by Jerrythemagicdog** 2019-10-30 01:15 UTC
Labels: confirmed
