### ISSUE TITLE
STV zep to UC drops you off at the edge

### ISSUE THREAD

**Issue by nhthor** [SunstriderEmu/BugTracker#2041] opened 2020-03-03 09:01 UTC
The zeppelin from STV to UC will drop off character at the very edge of STV causing players to fall off and die.

**Comment by SUN-Leekie** [comment] 2020-03-05 12:56
Is it happening 100% of the time or you got unlucky somehow?

**Comment by bisquiit** [comment] 2020-03-12 14:29
How is this not fixed its a known bugg since  opening of the server...

**Comment by SUN-Leekie** [comment] 2020-03-13 22:56
It would help a lot to have more information on this.

**Comment by artieau** [comment] 2020-03-28 13:42
Duplicate of #445

**Closed by artieau** 2020-03-28 13:42 UTC
Labels: question
