### ISSUE TITLE
Halaa Battle Tokens

### ISSUE THREAD

**Issue by danbilzerian23** [SunstriderEmu/BugTracker#3220] opened 2020-05-03 09:48 UTC
Hello. I have found it to be buggy with getting the Halaa Battle Tokens which you get when you get a killing blow on the opposit faction in This case killing a horde inside the area of Halaa in Nagrand. Back in tbc and on all other tbc private servers you Will get a token when you are killing a horde but on Endless it seems like i Only get a token when there are no guards left and the city is ”neutral” which is rather annoying because it takes 2 hours to clean out the guards solo and then when its unguarded people Come and retake it in 2minutes and i have no time at all to kill Any hordes by then. Would love to see This getting looked over and Perhaps fixed because its healthy for the world pvp aspect because you can get nice items for the tokens. Thank you:)
https://www.wowhead.com/item=26045/halaa-battle-token

**Comment by beraus** [comment] 2020-05-05 02:21
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3113

**Closed by beraus** 2020-05-05 02:21 UTC
