### ISSUE TITLE
Endless WOW shaman bug

### ISSUE THREAD

**Issue by Mandetta1234** [SunstriderEmu/BugTracker#4161] opened 2020-08-31 18:00 UTC
I discovered a new shaman bug, a guy told me that if you use Rockbiter on both weapons and pull the off hand to the main hand, the melee damage is doubled even after enchanting wind fury, I tested it on my shaman and this bug really happens, I ask kindly repair it, so that we can play fairly. Thank you.

Watch the video.

https://youtu.be/VfYfdJm0XVw

![WoWScrnShot_083120_134641](https://user-images.githubusercontent.com/70534381/91751041-81006880-eb9a-11ea-8d9c-d14812981bd8.jpg)
![WoWScrnShot_083120_134725](https://user-images.githubusercontent.com/70534381/91751064-88c00d00-eb9a-11ea-9af8-62a6f63d1133.jpg)
![WoWScrnShot_083120_134733](https://user-images.githubusercontent.com/70534381/91751081-8f4e8480-eb9a-11ea-9626-621fb9e8f8ee.jpg)
![WoWScrnShot_083120_134758](https://user-images.githubusercontent.com/70534381/91751101-97a6bf80-eb9a-11ea-948f-a3a8d3c76fdc.jpg)

**Comment by Jerrythemagicdog** [comment] 2020-08-31 19:52
Thanks, duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/3760

**Closed by Jerrythemagicdog** 2020-08-31 19:52 UTC

**Comment by Shamiroquai** [comment] 2020-09-09 20:08
OK now not eaven doing that the bug still happend. and now seems to be forever!!!. I NEED HELP.
