### ISSUE TITLE
[Dungeon] Party gaining Rest XP while running Scarlet Monastery.

### ISSUE THREAD

**Issue by Syfte-oss** [SunstriderEmu/BugTracker#2750] opened 2020-04-05 03:52 UTC
**Describe the bug**
We went to SM and ran the Library, the Armory and then the Cathedral.  While mid-way through the Library I noticed the Rest XP icon on my toon's frame.  I asked the party if they saw it as well and two others said Yes.  The remaining two may not have noticed the question.
This continued into the Armory.
I don't remember if I also saw it in the Cathedral.

**To Reproduce**
1. Go to Scarlet Monastery.
2. Bring your pajamas.

**Screenshots/videos**
https://i.imgur.com/EkAIrLQ.jpg

**Additional context**
If I wanted to sleep during a dungeon I'd play retail.  🤣

**Comment by Jerrythemagicdog** [comment] 2020-09-06 13:15
Can't reproduce, might've been fixed with something else, thanks!

**Closed by Jerrythemagicdog** 2020-09-06 13:15 UTC
