### ISSUE TITLE
Naxxramass - no trash loot

### ISSUE THREAD

**Issue by andrre69** [SunstriderEmu/BugTracker#3171] opened 2020-04-29 07:12 UTC
Except money, not even one trash mob drops what it should - cloths, warthorn scraps (T3 raegent) and epic items (pain point). Can you just turn trash loot on please? Killed approximatelly 40 mobs, and they all just dropped money.

Example - risen deathknight at the entrance should drop scraps and cloths, but drops only money.
https://tbcdb.com/?npc=16154

**Comment by Thorzovic** [comment] 2020-04-29 12:27
Boss are too without loot :)

**Comment by beraus** [comment] 2020-06-02 02:16
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3233

**Closed by beraus** 2020-06-02 02:16 UTC
