### ISSUE TITLE
Can't take the Karynaku quest

### ISSUE THREAD

**Issue by Jsanzo97** [SunstriderEmu/BugTracker#2850] opened 2020-04-09 19:03 UTC
I was doing the chain quest of Netherwings, when i reach the Karynaku quest called Zuluhed the Whacked i can't talk with the drake. I was in a group of 5 people and anybody can talk with it to start the quest

**Comment by beraus** [comment] 2020-04-10 03:40
https://github.com/SunstriderEmu/BugTracker/issues/2408

**Comment by Jerrythemagicdog** [comment] 2020-04-10 06:45
Thanks!
Duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/2408

**Closed by Jerrythemagicdog** 2020-04-10 06:45 UTC
