### ISSUE TITLE
Suppression (warlock quest)

### ISSUE THREAD

**Issue by teachmetolose** [SunstriderEmu/BugTracker#3421] opened 2020-05-18 07:10 UTC
**Describe the bug**
 Use "Glowing Crystal Prison" for "Doomguard Commander" As only start channeling it stopped, timer still going till 20sec and nothing happen in the end

**To Reproduce**
https://db.endless.gg/?quest=7583

**Expected behavior**
channeling must going till end of ritual, and not dropped, after that doomguard will input into crystal prison

**Comment by beraus** [comment] 2020-06-04 00:30
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2105

**Closed by beraus** 2020-06-04 00:30 UTC
Labels: quest
