### ISSUE TITLE
Frost Trap should not pull enemy from stealth

### ISSUE THREAD

**Issue by artieau** [SunstriderEmu/BugTracker#1657] opened 2020-01-10 11:24 UTC
**Describe the bug**
Hunters frost trap proc or area of effect tick currently pulls enemy from stealth.

**To Reproduce**
1. Hunter place frost trap
2.  Frost trap pop, area of effect on ground
3.  Stealth player run over area of frost and be pulled from stealth

**Expected behavior**
The stealthed player should be effected by the slow area, but not be pulled from stealth.

**Comment by kelno** [comment] 2020-05-30 08:13
Does it still?

**Comment by artieau** [comment] 2020-09-07 09:03
Yes it does still, rev. 15408 @kelno

**Comment by ghost** [comment] 2021-02-25 21:38
> A Hunter’s Frost Trap ground effect will break Rogues out of stealth.

[WoW Classic “Not A Bug” List - Updated Dec 3, 2020](https://us.forums.blizzard.com/en/wow/t/wow-classic-%E2%80%9Cnot-a-bug%E2%80%9D-list-updated-dec-3-2020/175887)

**Comment by kelno** [comment] 2021-02-26 14:05
Thanks, closing this then

**Closed by kelno** 2021-02-26 14:05 UTC
Labels: confirmed
