### ISSUE TITLE
Mage quest not working

### ISSUE THREAD

**Issue by Zsadist85** [SunstriderEmu/BugTracker#3684] opened 2020-06-12 01:19 UTC
**Describe the bug**
The mage quest called "Investigate the Alchemist Shop" is not generating anything.

**To Reproduce**

1. Cast Cantation of Manifestation
2. Creatures are supposed to appear
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
An invisible creature is supposed to appear for you to capture in a containment coffer.

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment] 2020-06-12 01:20
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2825

**Closed by beraus** 2020-06-12 01:20 UTC
