### ISSUE TITLE
Aspect of the viper passive regen generating threat

### ISSUE THREAD

**Issue by huntsmanjoe** [SunstriderEmu/BugTracker#3232] opened 2020-05-04 04:31 UTC
When using aspect of the viper, a hunter will passively gain threat due to mana regeneration. 

for example,  if you send your pet into 3 mobs,  two of the mobs that your pet is not hitting will immediately run after you because you caused threat by just regenerating mana through the permanent buff

this is incredible frustrating while solo questing especially.

**Comment by beraus** [comment] 2020-05-05 00:22
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2341

**Closed by beraus** 2020-05-05 00:22 UTC

**Comment by InhumanGM** [comment] 2020-05-17 16:11
Duplicate of #2679
