### ISSUE TITLE
Trinket interaction

### ISSUE THREAD

**Issue by Moiree** [SunstriderEmu/BugTracker#2369] opened 2020-03-17 01:55 UTC
Scryer's Bloodgem and Xi'ri's Gift share the full 1.5 min cooldown, probably due to the same exact on use effect.

**Comment by Woran123** [comment] 2020-03-21 08:17
I am having the exact same problem with these 2 trinkets.

**Comment by knoxz** [comment] 2020-03-27 23:58
you also get a super annoying animation bug and a constant humming effect after using the 2nd after the first one.
As the client thinks you should be able to use it after the first one expires.

**Comment by beraus** [comment] 2020-04-10 22:23
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087

**Closed** 2020-05-04 23:36 UTC
