### ISSUE TITLE
(Shaman) Water Totem Quest doesn't start

### ISSUE THREAD

**Issue by Xerxes789** [SunstriderEmu/BugTracker#3651] opened 2020-06-08 12:28 UTC
On my final shaman questline, i usualy get my water totem in silverpine forest. But I have done all the Prequests and the last one doesn't start, so i can't get my water totem :(
Can you help me plz?

**Comment by Keritous** [comment] 2020-06-08 14:14
You don't need to do chain quests to obtain totems. You can summon any totem.

**Comment by beraus** [comment] 2020-06-09 02:36
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3654

**Closed by beraus** 2020-06-09 02:36 UTC
Labels: quest
