### ISSUE TITLE
[Spell] Drunken Haze - 37591

### ISSUE THREAD

**Issue by BarrensJerk** [SunstriderEmu/BugTracker#650] opened 2019-02-22 02:41 UTC
**Description:**

Spell 37591 Drunken Haze cast by NPC 19957 Bloodmaul Brewmaster triggers a debuff and causes full screen glow drunken effect and staggering on walking / flying but spell effects don't drop off once debuff runs out or is dispelled, even minutes later

**Current behaviour:**

**Expected behaviour:**

Described as short acting effects on wowhead so I suspect it should be wwearing off, not persisting

https://www.wowhead.com/spell=37591/drunken-haze#comments

**Steps to reproduce the problem:**

1. Go fight a Bloodmaul Brewmaster
2. Get the debuff Drunken Haze
3. Wait for it to go away after killing mob
4. Keep waiting
5. Go to video settings and disable full screen glow effects 

**rev. hash/commit:** 

Sunstrider rev. 10530 (ec8fa6ac1145)

**Comment by Jerrythemagicdog** [comment] 2019-10-28 16:24
Tested, it does seem like the effect doesn't wear off (I've checked after 15 minutes and my character was still "smashed").

**Comment by kelno** [comment] 2019-10-28 19:49
Seems to wear of for me, hmm hmm

**Comment by Jerrythemagicdog** [comment] 2019-10-28 21:26
I apparently don't know how much 15 minutes is. Working as intended, wears off after ~10 minutes. Closing!

**Closed by Jerrythemagicdog** 2019-10-28 21:26 UTC
Labels: confirmed
