### ISSUE TITLE
Leotheras

### ISSUE THREAD

**Issue by frztw** [SunstriderEmu/BugTracker#3494] opened 2020-05-25 11:14 UTC
The aggro wipe can be overcome with a hunters Misdirection. Other tricks include having a shaman place a Searing Totem on the tanking spot (Leotheras will aggro this, allowing the MT to get aggro back easily). Bleeds or any other tank DoTs also help them gain aggro immediately when they tick after the aggro wipe. Having a Paladin main tank this encounter is also a good idea because he doesn't have to chase down Leotheras, but can simply throw an Avenger's Shield. **[Like most raid bosses, Leotheras is immune to taunt.](https://wowwiki.fandom.com/wiki/Leotheras_the_Blind?oldid=1593257)**

Now Leo was immune to taunt druid and warrior, palladin can use taunt

**Comment by bjh368** [comment] 2020-05-25 11:58
the problem isnt just leotheras, the problem is paladin taunt

**Comment by kelno** [comment] 2020-05-25 17:34
The taunt issue is already fixed and will be live with next server restart

**Comment by bjh368** [comment] 2020-05-26 19:05
That whole part is just a direct quote from the wowwiki page, its only the taunt part which is relevant here.

**Comment by frztw** [comment] 2020-05-26 19:12
Problem in a taunt, MD works correctly

**Comment by kelno** [comment] 2020-05-28 07:39
Okay then, if only the paladin taunt was the issue, this is now fixed.

**Closed by kelno** 2020-05-28 07:39 UTC
