### ISSUE TITLE
Netherstorm Quest Bugged

### ISSUE THREAD

**Issue by Khalexion** [SunstriderEmu/BugTracker#2611] opened 2020-03-29 06:34 UTC
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://www.wowhead.com/item=28452/bloodgem-shard#comments
Quest: https://www.wowhead.com/quest=10204/bloodgem-crystals
NPC: https://www.wowhead.com/npc=18855/sunfury-magister

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment] 2020-03-30 10:20
something weird is going on, the quest "works", but when I use the bloodgem shard I keep getting interrupted, had to go through 10 shards until the channel finally worked and then I completed the quest

**Comment by mechanicsTBC** [comment] 2020-04-01 19:54
it is bugged the same way most click and channel spells are bugged.  if you turn your character at all after starting the channel it will break the channel instantly.  for the bloodgems this means unless you are exactly facing the crystal when you use it, your character will turn slightly to face it and break the channel

**Comment by beraus** [comment] 2020-05-05 01:22
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2058

**Closed by beraus** 2020-05-05 01:22 UTC
Labels: confirmed
