### ISSUE TITLE
Mind Control breaking character control

### ISSUE THREAD

**Issue by emorelix** [SunstriderEmu/BugTracker#1178] opened 2019-04-26 09:26 UTC
**Description:**

Mind Control effect causes loss of control of character permanently, only fixed by relogging.

**Current behaviour:**
If a Priest mind controls me in pvp, arena, bg. I lose control of my character, permanently, until i relog. Even dying does not clear the loss of control.

**Expected behaviour:**

After MC breaks on a character, it should return control of your character without greying out your abilties or movement.

**Steps to reproduce the problem:**

1. Be Mc'd by a priest in pvp.
2. wait for mc to break or wear off
3. you now have loss of control of your character until you relog.

 **rev. hash/commit:** 	

Tested in 2v2 arenas and battlegrounds.

MC - spell=11446

![WoWScrnShot_042619_192424](https://user-images.githubusercontent.com/47015256/56797832-f2b6fc80-6858-11e9-9841-a95f049ca0f5.jpg)

**Comment by giveusmezpls** [comment] 2019-04-26 09:44
this happens sometimes but not all the time in PvE as well ,testable in Shadow Labs.
I found that it seems to be more likely when you have a loss of movement control whilst Mind Controlled (i.e. fear someone who is MC).

**Comment by emorelix** [comment] 2019-04-26 12:44
also from mechanar's last boss mc too

**Comment by Cheelout** [comment] 2019-05-08 23:26
To add to this I believe this issue may only be caused if the player is impacted by a crowd control effect WHILE MC'd. Two Cases:

1) We were doing Leotharas, Player got Mind Controlled - Was feared when killed / MC Released player due to death obviously. Player Battle Ressed and had no control
Future attempts players were just killed while Mind Controlled and revived with full control

2) Artist Mind Controlled Hooch in a 5's game, Broke without CC and Hooch had full control.

**Comment by kelno** [comment] 2019-05-09 13:50
Plz record haha

**Comment by kelno** [comment] 2019-05-15 15:32
More specific reproduce steps would help here (or a record on the PTR)

**Comment by kelno** [comment] 2019-07-26 11:09
Could be fixed by c2e83a0176ed16e5c3f9d445d5518375684d334c, maybe!

**Comment by kelno** [comment] 2019-09-07 04:03
Fixed until news

**Closed by kelno** 2019-09-07 04:03 UTC
Labels: confirmed, gamebreaking, movement, question
