### ISSUE TITLE
The Tome of Divinity aliance paladin dwarf

### ISSUE THREAD

**Issue by lackyss** [SunstriderEmu/BugTracker#2209] opened 2020-03-10 03:22 UTC
The resurrection quest does not work, after accepting the quest, the volume does not appear in the bag and the quest cannot be completed, correct the problem, add the ability study to the trainer, or fix my account, since I can no longer take the quest
![WoWScrnShot_031020_050837](https://user-images.githubusercontent.com/62001204/76276640-745c2100-6297-11ea-91ef-149378ca0bd3.jpg)
![WoWScrnShot_031020_050851](https://user-images.githubusercontent.com/62001204/76276646-79b96b80-6297-11ea-84bb-9b8cd5d779dc.jpg)

**Comment by InhumanGM** [comment] 2020-06-23 19:34
Duplicate of #3255

**Closed by InhumanGM** 2020-06-23 19:34 UTC
Labels: quest
