### ISSUE TITLE
Kylene does not offer cooking training

### ISSUE THREAD

**Issue by mechanicsTBC** [SunstriderEmu/BugTracker#2412] opened 2020-03-19 22:16 UTC
Kylene npc=19186
Gossip menu is missing, automatically opens shop.  Unable to access ability to learn cooking skills.  Also has an incorrect white item in inventory

**Comment by beraus** [comment] 2020-05-05 00:24
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2438

**Closed by beraus** 2020-05-05 00:24 UTC
