### ISSUE TITLE
Darnassus mount vendor

### ISSUE THREAD

**Issue by Keiz0r** [SunstriderEmu/BugTracker#2026] opened 2020-03-02 23:08 UTC
Darnassus mount vendor has all 6 mounts requiring 150 riding skill.
Please fix, and less treatment as an idiot
![Bug](https://user-images.githubusercontent.com/54153876/75726545-4b61ec00-5ceb-11ea-9313-c229a0afe349.jpg)

**Comment by gcdurastanti** [comment] 2020-04-10 14:37
I'm also seeing this issue. Any word on this?

**Comment by gcdurastanti** [comment] 2020-04-10 14:48
Update: Deleting Cache folder fixes this. Suggest closing.

**Comment by InhumanGM** [comment] 2020-05-14 13:36
> Update: Deleting Cache folder fixes this.

This is correct. The issue is caused by files in your cache folder, and removing these files fixes the issue.

**Closed by InhumanGM** 2020-05-14 13:36 UTC
