### ISSUE TITLE
Released spirit bugged on Undercity elevator

### ISSUE THREAD

**Issue by jvanrensburg69** [SunstriderEmu/BugTracker#3133] opened 2020-04-26 04:19 UTC
I ran all the way to Undercity to try and get the flight path, which took 15+ minutes. I died falling down the Undercity elevator, when I hit release spirit my ghost stayed in place with no option to resurrect. I re-logged and my ghost was teleported back to Tarren Mill, my hearth location.
**To Reproduce**

1. Die jumping down UC elevator
2. Release Spirit
3. Can't resurrect, so log out,
4. Log back in

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
I expected to be able to release spirit and go to the nearest graveyard, when I relogged, I expected to be at the nearest graveyard or at the same spot as when I logged out.

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment] 2020-05-04 23:40
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2257

**Closed by beraus** 2020-05-04 23:40 UTC
