### ISSUE TITLE
ELEMENTAL DEVASTATION BUGG - Reported Again 

### ISSUE THREAD

**Issue by Harvel218** [SunstriderEmu/BugTracker#3292] opened 2020-05-08 21:02 UTC
Elemental devastation is not procing on FLAMETONGUE WEPON CRITS ( it should proc)
i have checked it on 3 servers  (warmane, netherwing, nightbane) so please fix it, becouse it PISSES ME OFF that TALENTS are bugged and you are doing nothing about it.

*fun fact, flametongue wepon crit proc terestian trinket charges, and flametongue wep damage proc CRUSADER CARD BSD procs too.

I have tryed to screenshoot everything in time, but it didint worked, BUT you can see everything in combat log.

![WoWScrnShot_050820_225403](https://user-images.githubusercontent.com/59796176/81448954-8a933a00-917f-11ea-8bb7-1ceccfd48a9a.jpg)

![WoWScrnShot_050820_224540](https://user-images.githubusercontent.com/59796176/81448976-93840b80-917f-11ea-9687-6ef4e8c8f371.jpg)

![WoWScrnShot_050820_222903](https://user-images.githubusercontent.com/59796176/81448984-97b02900-917f-11ea-8a92-0d12353ec33f.jpg)

**Comment by beraus** [comment] 2020-05-26 23:20
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2670

**Closed by beraus** 2020-05-26 23:20 UTC
