### ISSUE TITLE
Judegement of crusader doesnt work well

### ISSUE THREAD

**Issue by Treaxx** [SunstriderEmu/BugTracker#3057] opened 2020-04-19 13:37 UTC
**Describe the bug**
 Judgement of crusader doesnt work well with Seal of righteousness since yesterday. it really boosts it a little and it is making every paladin spec unplayable pvp and pve. only holy pala is working cause he doesnt need to hit opponent with that. If he is not killing some 8k mob at the moment for 2 years ofc.

**Comment by Treaxx** [comment] 2020-04-19 13:39
Btw. There were another 2 topics around this and they seems to be gone. why are GMS not answering this question? Did some GM in bg while playing his character got knocked out by shockadin and is doing this?

**Comment by Ibuprofeno** [comment] 2020-04-19 14:36
They have apparently fixed JotC without fixing SoR scaling first. JotC isn't supposed to increase damage but holy spell power against the target. The problem is SoR isn't scaling properly with spellpower. At the moment with ~700 sp SoR hits for ~166 with a 1.8 weapon which is ridicolous.

**Comment by tankadin123** [comment] 2020-04-19 19:26
Can confirm this. Unable to tank HCs as prot specc, or so with great pain due to not being able to hold threat on bosses. Can't find anything about it in changelogs, so probably a bug since it been changed for roughly 36 hrs now, and no changelog update concerning the change.

**Comment by Felynda** [comment] 2020-04-19 21:27
You guys are crying without any proof. I made a quick google search and found a 9,2% spell damage scaling per 1 second of weapon speed. Now you are using an 1.8 second weapon so that means 9,2 * 1,8 = 16,56% spell damage scaling. This means that with with 700 spelldamage the damage per hit will be increased by only 116. 

source: https://wowwiki.fandom.com/wiki/Seal_of_Righteousness_(old)?oldid=1096995:

**Comment by tankadin123** [comment] 2020-04-19 22:32
Simply want to know if it was altered as a resort of a bug, or not. Since there's no changelogs on the matter.

**Comment by artieau** [comment] 2020-04-20 00:35
What is the issue and what should be the expected result?
Please post some information in your bug reports.

**Comment by oekbah** [comment] 2020-04-20 12:45
> What is the issue and what should be the expected result?
> Please post some information in your bug reports.

If memory serves, my Seal of Righteousness on a target judged with Seal of the Crusader used to deal 321 damage on hit. Now it deals 134 damage. This is with 269 spell damage.
I can not provide proof that the 321 damage was correct, but you can understand the frustration of such an extreme nerf. Less damage, less threat. 

It is already extremely difficult to tank some heroics as a prot pala, due to the extreme damage you take from bosses (Rokmar in SP Hc being an example, which is barely tankable on a t4-level geared prot paladin, in my experience).

Can you provide the reasoning behind this nerf/fix? Obviously many of us would prefer for it to be reverted, but an explanation might help people understand why they're suddenly dealing a fraction of their former damage.

**Comment by Ibuprofeno** [comment] 2020-04-20 16:42
> 
> 
> You guys are crying without any proof. I made a quick google search and found a 9,2% spell damage scaling per 1 second of weapon speed. Now you are using an 1.8 second weapon so that means 9,2 * 1,8 = 16,56% spell damage scaling. This means that with with 700 spelldamage the damage per hit will be increased by only 116.
> 
> source: https://wowwiki.fandom.com/wiki/Seal_of_Righteousness_(old)?oldid=1096995:

Except that formula comes from wowwiki comments from march-september 2007 as sourced in https://wowwiki.fandom.com/wiki/Talk:Seal_of_Righteousness_(old) and we're playing a patch released in july 2008.
With that formula this paladin with s1 weapon (1.6 wpn speed) https://youtu.be/BSS6F9UEIus?t=369 (hits for 261 with imp sor/crusade/sanctity (15% 10% 3%) which would make it ~204 without the talents) would need over 2k SD to hit for that amount.
In this one https://youtu.be/L7IGUjXvSGY?t=204 you can see him hit over 300.
SoR dmg is inconsistent throughout the videos anyway.

https://wowwiki.fandom.com/wiki/Patches/2.x release dates for 2.x patches. first is from april 2008 (~2.4.1) which is much closer to 2.4.3 (second one is a reupload but isle of quel'danas is out so it's at least 2.4) 

But it was a nice quick search.

**Comment by aadane** [comment] 2020-04-22 15:08
the judgement of Seal of Crusader gives a debuff on the target which increases the holy damage taken by 219. so the minimum dmg caused should be 219 + 43 which the dmg caused by seal of righteousness without any spell power. so anything below 262 is to low

**Comment by kelno** [comment] 2020-04-27 00:39
"holy damage taken by 219" > This is spell power only, not a flat 219 increase.

The only thing that changed is that Seal of righteousness damage has been corrected.
See https://github.com/SunstriderEmu/BugTracker/issues/1644

**Closed by kelno** 2020-04-27 00:39 UTC
Labels: question
