### ISSUE TITLE
Zepplin from Grom'gol to Undercity is bugged

### ISSUE THREAD

**Issue by whakahemo** [SunstriderEmu/BugTracker#3161] opened 2020-04-28 06:52 UTC
**Describe the bug**

When taking the Zepplin to Undercity from Grom'gol when it should show the map and the dotted line to UC the Zepplin disappears and drops you from the air and you die

Tried a couple times and it failed everytime - Also had other friends mention this as well

**Comment by beraus** [comment] 2020-04-28 12:11
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/445

**Comment by artieau** [comment] 2020-04-29 03:56
Duplicate of #445

**Closed by artieau** 2020-04-29 03:56 UTC

**Comment by whakahemo** [comment] 2020-05-04 08:19
So is this going to be fixed as it is still happening
