### ISSUE TITLE
Warpwood Pod - Dire Maul - Cooking

### ISSUE THREAD

**Issue by zeeqon** [SunstriderEmu/BugTracker#3201] opened 2020-05-01 10:23 UTC
Hello,

The only way to level cooking without fishing is to get the Runn Tum Tuber Surprise
It's a cooking recipe from Pusillin the Imp Boss in Dire Maul East

After you get the recipe you need to open Warpwood Pod's and get Runn Tum Tuber to craft the food which gets you to 285.
But the Pods won't open, I tried deleteing the cache + instance reset, I was able to open one of them once, but that was it.

Please fix this as it is the only way to level cooking without fishing (to the best of my knowledge).

Second bug in there is that Pusillin event is not scripted. He's supposed to run accross the instance once you spoke to him. But he just sits there at the entrace for you to kill.

Thanks and Kind Regards,
Heartofwild

**Comment by beraus** [comment] 2020-05-23 23:47
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2541

**Closed by beraus** 2020-05-23 23:47 UTC
