### ISSUE TITLE
Baron door opening event not working.

### ISSUE THREAD

**Issue by matejchi** [SunstriderEmu/BugTracker#3769] opened 2020-06-22 02:05 UTC
**Describe the bug**
Hello! 

When I defeat all the abominations in front of Baron Rivendares Ziggurat, the event doesn't start. From the entrance door of the Ziggurat,  Ramstein the Gorger should spawn and come out, he doesn't, and after that, some skeletons should come from the iron door on the right side of the Ziggurat room, they don't. That means that Baron Rivandares room door doesn't open, and i can't get to the boss. I'm farming the mount.

<!--- Please include ids of affected creatures / items / quests with a link to the relevant wowhead-

https://classic.wowhead.com/guides/undead-stratholme-classic-dungeon-strategy#baron-rivendare

**Expected behavior**
After you clear out the Abominations in the room, then from the entrance door of the Ziggurat,  Ramstein the Gorger should spawn and come out, he doesn't, and after that, some skeletons should come from the iron door on the right side of the Ziggurat room, they don't. That means that Baron Rivandares room door doesn't open, and i can't get to the boss. I'm farming the mount.

**Comment by beraus** [comment] 2020-06-22 02:26
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3569

**Closed by beraus** 2020-06-22 02:26 UTC
