### ISSUE TITLE
Badge of Justice issue

### ISSUE THREAD

**Issue by Phonebookhero** [SunstriderEmu/BugTracker#2446] opened 2020-03-20 23:50 UTC
**Describe the bug**
Finished heroic ramps, did last boss, badge dropped, upon clicking "Invalid target"

**To Reproduce**
See above

ramps id 436

**Expected behavior**

**Screenshots/videos**

**Additional context**
ramps id 436 - Alliance side

**Comment by B0nisek** [comment] 2020-03-21 11:50
yeah got this problem as well missed 6 bojs because of that so far

**Comment by mayday2013** [comment] 2020-03-23 08:18
That's why I run shadowplay when playing xD

**Comment by B0nisek** [comment] 2020-03-23 10:05
> That's why I'm using shadowplay when I play xD

what?

**Comment by mayday2013** [comment] 2020-03-23 20:50
Nvidia Geforce exp. their vid capturing software

**Comment by beraus** [comment] 2020-05-05 01:40
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2839

**Closed by beraus** 2020-05-05 01:40 UTC
