### ISSUE TITLE
Quest: The Second Trial

### ISSUE THREAD

**Issue by Macduff514** [SunstriderEmu/BugTracker#2527] opened 2020-03-24 19:53 UTC
**Describe the bug**
Accepted the quest which correctly spawns the crystal to start the battle event. However, once you click the crystal, no minions are summoned in order to complete the quest. 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by cobra7282** [comment] 2020-03-24 20:23
I also had an issue with this quest, but my issue was that it was showing as complete right after I accepted it. Therefor got credit for the quest without actually doing anything.

**Comment by InhumanGM** [comment] 2020-05-14 12:45
Duplicate of #3034

**Closed by InhumanGM** 2020-05-14 12:45 UTC
