### ISSUE TITLE
Heroic Strike off-hand miss chance. 

### ISSUE THREAD

**Issue by zanthed1** [SunstriderEmu/BugTracker#1556] opened 2019-12-25 02:22 UTC
Currently off-hand hits that occur while Heroic Strike is queued can miss while hit capped meaning that they suffer the dual wield penalty still.

All off-hand attacks that occur while Heroic Strike is queued should not suffer the dual wield penalty.

Proof:
https://blue.mmo-champion.com/topic/20036-warrior-dps-bugs/
https://us.forums.blizzard.com/en/wow/t/wow-classic-not-a-bug-list-updated-12-13-2019/175887
"Offhand attacks that occur while on-next-hit abilities such as Heroic Strike are queued do not suffer the dual wield to-hit penalty."

**Comment by networm555** [comment] 2019-12-25 07:10
you always have 1% miss no  matter what? ama wrong?

**Comment by zanthed1** [comment] 2019-12-25 07:26
You're thinking of spells. Melee doesn't have a mechanic like that

**Comment by kelno** [comment] 2019-12-25 08:48
Never heard of this before, thanks !

**Comment by Jerrythemagicdog** [comment] 2019-12-25 12:29
The first link is a bug report and Blizzard replying they will look into it. The second one is a source from Classic. 
This is a pretty big deal and might lead to class stacking (similarly to Vanilla) if it works the way it's described in the issue.

**Comment by Fettbergg** [comment] 2019-12-27 14:06
https://www.youtube.com/watch?v=Hn8eMD8zdOo

At 1:54 you can see the warrior missing an offhand hit while HS is queued.

**Comment by zanthed1** [comment] 2019-12-27 20:59
If you watch it very closely actually you can see he has a toggle for his HS key that he hits to turn it off when he is low rage. He does quite a few times throughout the fight. Play it on .25 speed and you'll see he turns it off, the miss happens, and he turns it back on very soon after to get the HS to land.

**Comment by Fettbergg** [comment] 2019-12-28 11:55
There are 2 misses right after another. Playing it on .25 for the 10th time and as far as i can tell the first miss happens while hs is queued.

**Comment by zanthed1** [comment] 2019-12-28 12:10
With the way batch windows work the swing (probably) landed while he wasn't queued which is when all the rolls are done, and swing damage landed (in this case a miss) while it was queued.

**Comment by Fettbergg** [comment] 2019-12-28 21:12
I dont know but to me this video clearly shows the opposite of what is stated in the title. I like to be proven wrong however.

Cheers

**Comment by knasen88** [comment] 2020-02-26 22:45
this is pretty big part of woyer dps, pls fix
Seeing the rogues gem for 17% hit while we can ride 9% is an added bonus

**Comment by knasen88** [comment] 2020-02-26 22:58
https://i.imgur.com/DtORlIG.png
@Fettbergg at 1:53
He has his combat log open realtime so you have to look at that, numbers are ALWAYS delayed in game.
First his heroic strike LANDS
Presses BT
Misses OH
Queues HS

**Comment by dshgrove** [comment] 2020-04-05 12:47
Bump. This is an integral part of warrior dps and currently a massive loss.
Atleast reply to the comment given or give us incentive to provide further proof. It is also a big reason to why warriors scale so well with gear, since you get more rage, more heroic strikes, which gives more offhand hits, more rage.. and so on..

**Comment by kelno** [comment] 2020-05-30 10:36
Well if that's a "not a bug" in Classic, and proven to also exists in WotLK... That's good enough proof for me.

**Comment by kelno** [comment] 2020-05-31 07:28
Fixed with next update

**Closed by kelno** 2020-05-31 07:28 UTC
Labels: confirmed, core
