### ISSUE TITLE
[Quest] Boiling Blood when you turn the blood into the cauldron scarabs are currently not spawning

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1568] opened 2019-12-28 07:19 UTC
The "Boiling Blood" quest in Hellfire Peninsula during the hand-in of the blood to the cauldron each hand-in should be spawning several scarabs, but currently no scarabs spawn at all as can be seen in https://streamable.com/e3ljp

**Comment by Jerrythemagicdog** [comment] 2019-12-28 11:03
I can't reproduce reliably, they do spawn after a 1-2 second delay, then turn hostile and start attacking the player. 
Perhaps some range restriction happening again.

**Comment by maingaming** [comment] 2020-01-12 14:44
I've tested the quest on my SP and can't confirm that. The scarabs spawn after a long delay (~3sec), are neutral at first and then start attacking the player. However, you can just run away and reset the scarab spawns which will despawn. Due to the delay, you can spam-click the cauldron and create lots of blood before scarabs spawn, then run away, reset and repeat until done. I'm not sure how it is supposed to be "blizzlike". Not a big issue if you ask me, tho.

**Comment by blblblaz** [comment] 2020-01-18 22:19
closing it until somebody confirms, can't reproduce

**Closed** 2020-01-18 22:18 UTC
