### ISSUE TITLE
Chest in dungeon

### ISSUE THREAD

**Issue by elnium123** [SunstriderEmu/BugTracker#2505] opened 2020-03-23 15:04 UTC
They are 2 chest lock in mechanar and on auchenai & setekh too on retail server, but they are not spawn here, can you do something mby?

https://www.youtube.com/watch?v=ShTe7aEwlOo&t=256s
https://www.youtube.com/watch?v=ld-NtQwWvG4&t=218s
https://www.youtube.com/watch?v=-upbUldmt38

Thx for mby fix that.

**Comment by elnium123** [comment] 2020-03-25 07:57
?????????

**Comment by beraus** [comment] 2020-05-31 01:09
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1681

**Closed by beraus** 2020-05-31 01:09 UTC
