### ISSUE TITLE
[Quest] The Fare of Lar'korwi

### ISSUE THREAD

**Issue by jamesevans28** [SunstriderEmu/BugTracker#868] opened 2019-03-24 22:26 UTC
**Description:**

The quest: The Fare of Lar'korwi in Ungoro doesnt allow me to loot the item from the carcass. I click on it and it takes time to open, then nothing happens. Click again and it says the item is already being used.

**Current behaviour:**

Clicking on the carcass starts the progress bar, but when complete nothing happens. No loot or quest completion. 

**Expected behaviour:**

An item should be lootable upon the completion of the loot progress. 

**Steps to reproduce the problem:**

1. Acquire the quest The Far of Law'korwi in Ungoro from Torwa Pathfinder (71,76)
2. Find the carcass (68,56) and click on it to loot
3. Observe the progress bar completing, but no loot window popup. 
4. Click on the carcass again, observe the error message: this item is already being used. 

**rev. hash/commit:** 

CHANGEME

![image](https://user-images.githubusercontent.com/14988275/54886783-da616400-4edf-11e9-938e-4933b9d267be.png)

**Comment by jamesevans28** [comment] 2019-04-02 21:57
Apparently you can click on different parts of the carcass and it works, however the action cursor is highlighted for all areas of the carcass.

**Comment by Jerrythemagicdog** [comment] 2019-10-28 00:38
Tested now, can't reproduce.
Possibly fixed with the loot rework.

**Closed by Jerrythemagicdog** 2019-10-28 00:38 UTC
Labels: vanilla
