### ISSUE TITLE
Undercity <-> Grom'Gol Zeppelin doesn't work

### ISSUE THREAD

**Issue by steak-house** [SunstriderEmu/BugTracker#2853] opened 2020-04-09 20:15 UTC
**Describe the bug**
* The zeppelin never shows up in Tirisfal Glades
* If you take the Zepp from Grom'Gol to Undercity, it will despawn when it reaches the teleport point and you will fall to your death

**Comment by Mfunn** [comment] 2020-04-19 18:54
+1 grom gol -> undercity zeppelin dropping you to your death

**Comment by catrap123** [comment] 2020-04-23 00:56
+1 Waited in Tirisfal for 15 minutes before deciding to check the bug tracker.

**Comment by artieau** [comment] 2020-04-29 03:56
Duplicate of #445

**Closed by artieau** 2020-04-29 03:56 UTC

**Comment by steak-house** [comment] 2020-04-29 13:45
Not really... The problem described in the issue you linked is that the zepp hangs, but eventually reaches its destination. What I describe, and what was confirmed by another player, is that the grom gol zeppelin never shows up in undercity. Please reopen.
