### ISSUE TITLE
Bugged Zeppelin from Grom'gol Base Camp to UC

### ISSUE THREAD

**Issue by shrift1** [SunstriderEmu/BugTracker#2422] opened 2020-03-20 08:27 UTC
Bugged Zeppelin
Zeppelin from Grom'gol Base Camp to Undercity
![WoWScrnShot_031820_153154](https://user-images.githubusercontent.com/31934397/77147125-e77e4800-6a8c-11ea-8db8-870a7560e71c.jpg)
![WoWScrnShot_031820_153150](https://user-images.githubusercontent.com/31934397/77147127-e9480b80-6a8c-11ea-888b-0069aaf8b1fc.jpg)

I fell twice and died from fall damage :(

**Comment by Jerrythemagicdog** [comment] 2020-03-20 17:54
Thanks, working on it!

**Comment by artieau** [comment] 2020-03-28 13:42
Duplicate of #445

**Closed by artieau** 2020-03-28 13:42 UTC
Labels: confirmed, core
