### ISSUE TITLE
Can't create Deadly Poison V

### ISSUE THREAD

**Issue by Hedzikk95** [SunstriderEmu/BugTracker#2487] opened 2020-03-22 19:42 UTC
**I can't create Deadly Poison V as a 64 Rogue. I have all the right mats and i have max skill.. I have done all the rogue quests except for a Dungeon one.. but it shouldn't effect the problem i have..**
I'm a human female Rogue, lvl 64, Called Dabii
When i press Create when i choose Deadly Poison V it says "Item is not ready yet"
I can create all the other before the V but not that one.

![WoWScrnShot_032220_203319](https://user-images.githubusercontent.com/62519699/77258847-88cbf080-6c7d-11ea-89a1-f8ac1e0bca51.jpg)

**Comment by Jerrythemagicdog** [comment] 2020-03-22 19:55
Thanks! Closing as it's a duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2474

**Closed by Jerrythemagicdog** 2020-03-22 19:55 UTC
