### ISSUE TITLE
The Second Trial quest (Bloodelf Paladin)

### ISSUE THREAD

**Issue by knuper** [SunstriderEmu/BugTracker#2758] opened 2020-04-05 12:17 UTC
The quest can be taken from the NPC : Master Kelerun Bloodmourn, but cannot be achieved.
You are able to use the crystal as specified in the description, but nothing happens : the NPCs you have to fight to complete the quest don't pop.

**Comment by InhumanGM** [comment] 2020-05-14 12:45
Duplicate of #3034

**Closed by InhumanGM** 2020-05-14 12:45 UTC
