### ISSUE TITLE
[Hunter] Misdirection Issues

### ISSUE THREAD

**Issue by Shmoe264** [SunstriderEmu/BugTracker#2701] opened 2020-04-02 19:14 UTC
**Describe the bug**
Misdirection on hunters should be applied to their first three hits on any target. Right now, it is only being applied to single targets or having to shoot targets individually for the first three shots, so multi-shot MDing is not working. Additionally, MDs can be overlapped by other hunters, which should not be the case.

Based on the spell info, "Caster and target can only be affected by one Misdirection spell at a time." With this, you should not be able to overwrite one hunter's MD with another hunter's MD on the same player.

**To Reproduce**
1. Cast misdirection on another player.
2. Cast multi-shot once on three mobs.
3. Confirm if all mobs have threat on the player with MD.
4. Additionally, have one hunter MD a player, and have another hunter MD the same player and confirm if it is overwritten.

**Comment by mchayes** [comment] 2020-04-03 10:22
Also frost trap is consuming MD charges.

**Comment by Shmoe264** [comment] 2020-06-01 19:22
Hunter's Mark is also consuming an MD charge.

**Comment by kelno** [comment] 2020-06-16 08:20
Putting "confirmed" for the single target part.

The overwrite part lacks details so here's what I found: 
Patch 2.3.0 (13-Nov-2007): This spell will now always be removed correctly if multiple Hunters overwrite each other’s Misdirection.; If a Hunter attempts to use this ability on a target which already has an active Misdirection, the spell will fail to apply due to a more powerful spell already being in effect. This will not trigger the cooldown or cost any mana.

**Comment by kelno** [comment] 2020-06-16 08:40
Fixed the overwrite part, applied with next update

**Comment by kelno** [comment] 2020-06-16 08:59
I couldn't reproduce the main issue:
https://streamable.com/ckrh2p

What am I missing?

**Comment by kelno** [comment] 2020-06-16 09:11
Fixed misdirect being consumed by Hunter's Mark or Frost Trap (or many non damaging spells), applied with next update

**Comment by mechanicsTBC** [comment] 2020-06-18 06:40
The previous issue was that misdirection was able to be stacked, which was a wrath 3.3 thing https://wowwiki.fandom.com/wiki/Patch_3.3.0.  That was fixed with this update.  The new problem that should be fixed at the same time is misdirection is not being consumed on the tank after the hunter performs 3 attacks. 

Cast MD on tank, do 3 shots.  Tank gets threat from all 3 shots.  Tank still has misdirection buff on him so new misdirection can not be applied for remaining buff time.  Seems the buffs are not properly linked and the tank gets a separate, incorrect misdirect buff that is not linked with the buff the hunter has.

**Comment by kelno** [comment] 2020-06-18 12:36
Alright that's a big issue, thanks for details, I'll check that now

**Comment by kelno** [comment] 2020-06-18 13:36
Fixed with next restart (in 45min)

**Closed by kelno** 2020-06-18 13:36 UTC
Labels: confirmed, core, question, spells
