### ISSUE TITLE
Zeppelin between Undercity and Grom'Gol

### ISSUE THREAD

**Issue by Norppalyr** [SunstriderEmu/BugTracker#2568] opened 2020-03-27 08:59 UTC
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

1. Waiting for the zeppelin at Tirisfal Glades. It never came. Waited and waited. 
2. Tried to get from STV to UC. Hopped on the zeppelin at Grom'Gol. "Fell off" somewhere close to Rebel Camp (the zeppelin just disappeared from under me). Resurrected, went back and tried it again. Same thing happened. Took the zeppelin to Durotar and went to Tirisfal Glades from there, worked just fine. 
Conclusion: Does the Undercity - Grom'Gol zeppelin exist/function?

**Comment by artieau** [comment] 2020-03-28 13:42
Duplicate of #445

**Closed by artieau** 2020-03-28 13:42 UTC
