### ISSUE TITLE
Scryer's Bloodgem and Xi'Ri's Gift share 90s cooldown instead of 15s.

### ISSUE THREAD

**Issue by Klappe** [SunstriderEmu/BugTracker#2942] opened 2020-04-13 08:53 UTC
When you have both Scryer's Bloodgem and Xi'Ri's Gift equipped they are supposed to share a 15s cooldown so you can't stack both effects on top of eachother. However, when you use one of them you can't use the other one for 90 seconds instead. The tooltip shows that you get a 15s cd for the other trinket when you use one but when you try to use it after 15s your character just gets stuck with the casting animation until you use it again after 90s.

**To Reproduce**
1. Equip Scryer's Bloodgem and Xi'Ri's Gift.
2. Use either on of them.
3. Wait 15 seconds.
4. Try to use the second trinket.

https://www.wowhead.com/item=29132/scryers-bloodgem
https://www.wowhead.com/item=29179/xiris-gift

**Comment by knoxz** [comment] 2020-04-29 21:45
https://github.com/SunstriderEmu/BugTracker/issues/2087

**Comment by beraus** [comment] 2020-05-04 23:38
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087

**Closed by beraus** 2020-05-04 23:38 UTC
