### ISSUE TITLE
Arena team charter

### ISSUE THREAD

**Issue by Macumbafeh** [SunstriderEmu/BugTracker#2297] opened 2020-03-13 22:41 UTC
**Describe the bug**
If you log out without bring back the Arena team charter, then the charter vanish...
It happened to with 3v3 team charter. Didn't Try with other charter. I don't have any gold now >>

**To Reproduce**
Take a 3v3 Arena team charter, then log out, and it vanish

**Expected behavior**
A Arena team charter don't have to vanish, even if you log out.

**Comment by SUN-Leekie** [comment] 2020-03-13 23:00
Cannot reproduce, can you provide more information on what happened before you logged off? Was it a crash?

**Comment by Macumbafeh** [comment] 2020-03-14 17:01
Maybe it was a crash i don't know... I just know i bought a 3v3 team and before it, i had 160g.
Now i have 40 gold and no charter anywhere...
So no without money i can't reproduce unfort...

**Comment by Sheikthecatman** [comment] 2020-04-28 20:18
Closing as it has been fixed.

**Closed by Sheikthecatman** 2020-04-28 20:18 UTC
Labels: question
