### ISSUE TITLE
Felstalker Quest

### ISSUE THREAD

**Issue by xEnvoy** [SunstriderEmu/BugTracker#3385] opened 2020-05-15 22:57 UTC
**Describe the bug**
Last part of the Felstalker quest you summon it and kill it and it doesn't complete quest.

**To Reproduce**
Idk

https://classic.wowhead.com/quest=1795/the-binding
**Expected behavior**
Kill felstalker and the quest completes

**Comment by InhumanGM** [comment] 2020-05-15 23:12
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by xEnvoy** [comment] 2020-05-15 23:13
I dont think so i just accepted the quest and summoned it killed it and its not completing it.
________________________________

**Comment by InhumanGM** [comment] 2020-05-15 23:17
Are you able to try again?

**Comment by xEnvoy** [comment] 2020-05-15 23:20
worked that time, after the 10th try :p thank you
________________________________

**Comment by InhumanGM** [comment] 2020-05-16 01:43
Sounds good, I'll be closing this as the issue is unable to be reproduced.

**Closed by InhumanGM** 2020-05-16 01:43 UTC
Labels: quest, question
