### ISSUE TITLE
One of the SSC Morogrim murloc packs pulls the boss.

### ISSUE THREAD

**Issue by frastsytt** [SunstriderEmu/BugTracker#3318] opened 2020-05-11 07:30 UTC
In general the murloc packs in Morogrims room have an insane aggro radius, which I think this issue stems from. If that's how you wish it to be tuned then that's fine.

However, there is currently a pack of patrolling murlocs that pulls Morogrim Tidewalker when you aggro them ontop of the ramp, this shouldn't happen.

![image](https://user-images.githubusercontent.com/57603552/81535185-0359e800-9372-11ea-8463-095cfc83053f.png)

Video of how it's supposed to be:
https://youtu.be/0IWGcMWob6k?t=988

Notice how the last murloc pack is pulled, boss doesnt leash off it and then the warlock in the grp Chaos Bolts the boss and aggros it.

**Comment by mechanicsTBC** [comment] 2020-05-12 14:40
This pack pulls the boss as well when on the left and right side of the boss.  The only way to pull it and not have it aggro the boss is to pull it from the back of the room (top side of the picture shown above).  Most likely caused by the massive aggro radius the murlocs have as mentioned.

**Comment by Mihai930** [comment] 2020-05-12 23:00
you can pull from the left side of the boss.

https://clips.twitch.tv/PluckyAnimatedBunnyRedCoat

**Comment by Jerrythemagicdog** [comment] 2020-05-13 18:13
Thanks, fixed with next update.

**Closed** 2020-05-13 18:13 UTC
