### ISSUE TITLE
Diremaul East - Warpwood Pods 

### ISSUE THREAD

**Issue by Graszelda** [SunstriderEmu/BugTracker#2277] opened 2020-03-12 22:36 UTC
Some Warpwood Pods inside Diremaul Easts are not opening when clicked on.  It is not limited to specific locations and is random.

**Comment by beraus** [comment] 2020-05-04 23:20
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2541

**Closed by beraus** 2020-05-04 23:20 UTC
