### ISSUE TITLE
combat timer

### ISSUE THREAD

**Issue by tbc123** [SunstriderEmu/BugTracker#4261] opened 2020-09-22 19:39 UTC
Combat timer should be from 4.5 to 6.5 seconds.
It is not random, but rather works in a similar manner to the DR timer.

Combat timer is 4.5 seconds, but the server checks in a 2 second interval whether combat has expired. This 2 second timer, is the same time that is responsible for energy ticks.

This same timer is also the same timer responsible for the so called "5 second rule", which activates non-combat mana regeneration in combat.

https://www.youtube.com/watch?v=6cMJFN-eNRU&t=1m10s
The above video very clearly shows it being linked to combat timer. Woundman also has an addon that tracks how long it has been since the last "combat action", counting down from 5 seconds. It's the best and most memorable evidence, although I remember seeing a video where someone restealthed after improved gouge (5.5 seconds), dropping combat before the duration ended.

**Comment by beraus** [comment] 2020-09-22 19:42
This is your 3rd duplicate of the same issue. 
https://github.com/SunstriderEmu/BugTracker/issues/4204 
https://github.com/SunstriderEmu/BugTracker/issues/4208

**Closed by beraus** 2020-09-22 19:42 UTC

**Comment by tbc123** [comment] 2020-09-22 19:48
> This is your 3rd duplicate of the same issue.
> #4204
> #4208

yea but im right if its blizlike make like blizlike dont do costumize stuff cuz its wrong...
