### ISSUE TITLE
Felwood Corrupted Herbs

### ISSUE THREAD

**Issue by klankin** [SunstriderEmu/BugTracker#3414] opened 2020-05-17 21:10 UTC
cleansing the herbs in felwood is not rewarding any plants. in the case of the corrupted night dragon, myself and another player both tried to cleanse the plant with the salve and both were not rewarded anything. 

![WoWScrnShot_051720_171156](https://user-images.githubusercontent.com/17366512/82160241-ee91be80-9861-11ea-8a69-08b0c14b4112.jpg)

https://classic.wowhead.com/object=164885/corrupted-night-dragon
https://classic.wowhead.com/item=11952/night-dragons-breath

**Comment by beraus** [comment] 2020-05-31 02:04
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3285

**Closed by beraus** 2020-05-31 02:04 UTC
