### ISSUE TITLE
Critical strike bugged

### ISSUE THREAD

**Issue by cartermatic1989** [SunstriderEmu/BugTracker#2534] opened 2020-03-25 10:07 UTC
**Describe the bug**For example when someone its eating or driking or simple lay down pressing "X" key and you come from behind striking him... should be 100 % critical... but its not working.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment] 2020-05-05 01:32
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1855

**Closed by beraus** 2020-05-05 01:32 UTC
