### ISSUE TITLE
Kindness-quest in smw

### ISSUE THREAD

**Issue by shotinveins** [SunstriderEmu/BugTracker#2549] opened 2020-03-26 00:03 UTC
**Describe the bug**
<Dragons dont fly down after using quest item to lure them down>

**Expected behavior**
<So after you get item from bug looking creatures you place it on the ground and the dragom should fly down. But me and my mate used like 20 of those to get them down and nothing happened. We evem tried to time it whem they were above us bit still nothing. Quest is working because i see some people using quest items from that chain quest but i guess its not 100% clean. I quit after 20 tries but i have to do it to begin attune chain so...ye it would be if you could look into it.>

Thank you and keep up the good work!!!

**Comment by ageerik** [comment] 2020-03-28 09:27
same for me and my friends, been here for 30min nothing happend

**Comment by blblblaz** [comment] 2020-03-28 15:02
the quest is completable and plenty of people have completed the entire quest chain, the reason why you sometimes don't get a drake to come down is because the drakes aren't exactly where they appear to be, which is why sometimes none of them come down, or it could also be because they were already "fed", we can look into making it more "smooth" to complete but for now, sadly, my suggestion is to keep trying until you get it.

**Comment by ageerik** [comment] 2020-03-28 17:20
Yes, it is possible to complete it, I got 3/8 before I went away. We were 5 people in the group having the problem and other people around writing the same thing, That's not how it should be. We also found out that it only worked if you stood completely still after planting the bait. But something needs to be done, this is not how it should work.

**Comment by shotinveins** [comment] 2020-03-29 11:46
ive menaged to complete it. okay so for all of you who are stuck on this quest. there a hill at very start of that walley. farm as much of quest items as you can and get on it. you have to place it pretty much perfectly when dragon is above you or a second or so before.its a bit hard you'll not get it on your first try but its doable and 100% working ive done it. GL with it

**Comment by artieau** [comment] 2020-04-08 08:41
The Drakes have a de-sync issue after a period of time on live server - confirmed twice now.
Resetting them shows this and returns to normal behavior for a period of time.

**Comment by artieau** [comment] 2020-04-08 09:06
Fixed next restart

**Comment by Balanarr** [comment] 2020-04-14 15:17
Tried around 20 times, drakes close, no drakes close, ground, hill, crystal ... nothing
If you haven't gotten angry in a while and feel like you want to, try to do this quest.

**Comment by Stolemyname1** [comment] 2020-04-17 03:05
Also tried tonight, tried not moving, nothing worked.

**Comment by kelno** [comment] 2020-05-03 16:33
Fixed

**Comment by beraus** [comment] 2020-05-06 03:19
Getting ticket about this quest after 30+ hours on live server.

**Comment by InhumanGM** [comment] 2020-05-16 01:55
This issue was fixed in #3172.

**Comment by beraus** [comment] 2020-05-23 23:35
@kelno Looks like it doesn't work properly after very long server uptime (30+ hours).

**Comment by kelno** [comment] 2020-06-27 17:12
Related https://github.com/TrinityCore/TrinityCore/issues/22448#issuecomment-650581766

**Comment by Jerrythemagicdog** [comment] 2020-09-01 01:10
Fixed in '1d4697e1ef9864ba645cf562afcbacbdccdcd569'

**Closed by Jerrythemagicdog** 2020-09-01 01:10 UTC
Labels: confirmed, quest
