### ISSUE TITLE
Gamebreaking Trinket Bug

### ISSUE THREAD

**Issue by johncguti** [SunstriderEmu/BugTracker#2087] opened 2020-03-04 14:58 UTC
**Describe the bug**
When using 2 spellpower trinkets, specifically  [Scryer's Bloodgem] [Xi'ri's Gift] , After I activate the first trinket, wait 15 seconds, and activate the second (as a should be able to) the second trinket does not activate (shares entire cooldown with first) and more importantly causes a casting animation (portal casting) to no end.  In other words, you cant use two trinkets the way you should be able to. 
 
Other players observing my character CANNOT see the casting animation I am making that is caused by the trinkets bugging out, only I can see it. 

**To Reproduce**
1. Use  [Scryer's Bloodgem] 
2. Wait 15 seconds until cooldown is up
3. Use  [Xi'ri's Gift] (it wont work)

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page.

**Expected behavior**
You should be able to use your second trinket after the 15 second cooldown. 

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by SUN-Leekie** [comment] 2020-03-05 01:07
Confirmed on cannot use the trinket but other players were able to see the animation of my casts while it was bugged for the caster.

**Comment by Isklar** [comment] 2020-05-02 00:26
Seems to affect any trinkets with the same two buffs.
[[Vengeance of the Illidari]](https://tbc-twinhead.twinstar.cz/?item=28040) and [[Ancient Draenei Arcane Relic] ](https://tbc-twinhead.twinstar.cz/?item=31615)also suffer from this problem (spell dmg +120 etc)

**Comment by beraus** [comment] 2020-06-13 02:10
Looks like it affect 2 more trinkets; 
Marc: Bladefists breadth and ancient dranei war talisman. They are both ap buffs, same amount of AP, both 1.30m cds. Seems as if the server recognises them as the same trinket.

**Comment by deppierre** [comment] 2020-07-15 01:49
Is there any update on this issue? I mean its really annoying that I cant use 2 trinkets in a row

**Comment by hufsa** [comment] 2020-09-04 07:21
Thank you! Fixed with next update.

**Closed by hufsa** 2020-09-04 07:21 UTC
Labels: confirmed
