### ISSUE TITLE
Stratholme Dungeon Baron Event bugged

### ISSUE THREAD

**Issue by layalaa** [SunstriderEmu/BugTracker#2796] opened 2020-04-07 01:26 UTC
1) The Bonespewer Adds infront of the Baron Endboss are wierdly connected to each other. Sometimes 3 Mobs coming at once and there is no time for recover after defeat, because new spewers are coming.

2) Once you killed all Adds the Door still won't open

**Comment by beraus** [comment] 2020-06-22 02:26
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3569

**Closed by beraus** 2020-06-22 02:26 UTC
