### ISSUE TITLE
Quest - Bloodmyst Isle - Ending their world

### ISSUE THREAD

**Issue by Thanafer** [SunstriderEmu/BugTracker#2295] opened 2020-03-13 20:47 UTC
Given by Demolitionsit Legoso, it triggers an escort event who works until the end of his path, when Legoso face Sironas and didn't trigger the fight. He just disappears and the objective of the quest stays incomplete. This quest rewards the tabard of the hand with the next quest, which is a nice flavor item. Thanks for your work !

**Comment by Samaell99** [comment] 2020-03-28 16:23
Yeah i got to the quest too. It's bugged. 
Here is the quest link for wowhead: https://www.wowhead.com/quest=9759/ending-their-world

**Comment by beraus** [comment] 2020-05-05 01:52
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1956

**Closed by beraus** 2020-05-05 01:52 UTC
