### ISSUE TITLE
Stuck in ghost mode

### ISSUE THREAD

**Issue by sraniewbanie** [SunstriderEmu/BugTracker#3467] opened 2020-05-22 17:36 UTC
**Describe the bug**
I died in elevator in UC because of bug. Then i get ghost mode in elevator already but the revive button does not appear. My corpes are invisible, been to graveyard - nothing happened. Im like stuck. Cant see people, cant see NPC, only textures. Tried already Unstuck by website - it said that i'm teleported to closest graveyard but nothing happened.

caracter's name Kubraczek. 
Shaman 33lvl
**Expected behaviour**
Resurect and teleport me please.

**Screenshots/videos**
https://i.gyazo.com/a4a4fa861ccbfa538108c153cd0dd007.jpg
https://i.gyazo.com/b4856e0d12a2903c2c77447ce18826b4.jpg

**Comment by InhumanGM** [comment] 2020-05-22 18:33
Duplicate of #2257

**Closed by InhumanGM** 2020-05-22 18:33 UTC
