### ISSUE TITLE
Shadowmoonvalley Quest Kindness: No credits given

### ISSUE THREAD

**Issue by Vitamalz** [SunstriderEmu/BugTracker#2720] opened 2020-04-03 16:58 UTC
**Describe the bug**

QuestID: 10804 (retail wowhead)

Netherdrakes do not accept food offerings; resulting in no quest progression.
Fooditem ID: 31372 (Rocknail Flayer Carcass)
To be fed at around: 62/56 in SMV (or east of Sanctum of the Stars)

**To Reproduce**

Just attempt to feed the drakes

Item: https://wowhead.com?item=31372
Quest: https://wowhead.com?quest=10804

**Expected behavior**

Netherdrakes are supposed to fly towards the meat, eat it, thank you and fly off resulting in credit given

**Screenshots/videos**

**Additional context**

**Comment by beraus** [comment] 2020-05-03 02:10
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2549

**Closed** 2020-05-05 00:08 UTC
