### ISSUE TITLE
Aspect of the Viper, dot work mana regneration from intelect part

### ISSUE THREAD

**Issue by spllash** [SunstriderEmu/BugTracker#3575] opened 2020-05-31 16:21 UTC
Spell: https://www.wowhead.com/forums&topic=49398/aspect-of-the-viper
Its regenerait only 24 mana, its 35% fron lvl at 70lvl
its must regenerate 35% from lvl and 55% from intelect.
Regeneratoin from intelect  part  dont work

**Comment by InhumanGM** [comment] 2020-05-31 17:49
Duplicate of #2679

**Closed by InhumanGM** 2020-05-31 17:49 UTC
