### ISSUE TITLE
Kara - Prince Malchezaar - Two bugged mechanics in Phase 3

### ISSUE THREAD

**Issue by Godmatik** [SunstriderEmu/BugTracker#2590] opened 2020-03-28 07:06 UTC
Amplify Damage debuff - he is supposed to only place this on one target. But when he casts it, he is debuffing all 10 raid members every time instead.

Flying Axes - The axes hit for an incredibly low amount of damage. It should be the main source of damage and issues you have to heal through in phase 3, but they are just not a factor, hitting for only a couple hundred damage or so with each swing. It's possible they are missing the "Demonic Frenzy" buff (described below).

Source:
https://wowwiki.fandom.com/wiki/Prince_Malchezaar

> Flying Axes (Phase Three)

> Malchezaar unleashes his axes on random targets as a separate but untargetable attacking entity. They deal physical damage and appear to have Demonic Frenzy as they start out hitting each new target for only about 400 on cloth, while ramping up to 2000 a hit.

> Amplify Damage (Phase Three)

> Amplify Damage is a debuff that doubles damage taken from all sources. It is cast on a random target and not dispellable.

**Comment by artieau** [comment] 2020-03-28 12:37
Amplify debuff is working as intended.
Closing this as duplicate for Flying Axes #2198

**Closed by artieau** 2020-03-28 12:37 UTC
