### ISSUE TITLE
Xi'ri's Gift AndScryer's Bloodgem Bugged interaction

### ISSUE THREAD

**Issue by kankertiefus** [SunstriderEmu/BugTracker#2496] opened 2020-03-23 04:50 UTC
**Describe the bug**
When you use 1 of these trinkets, it puts the other trinket on a 15s cooldown. Nothing wrong there.
BUT when you then try to use the other trinket, you get: 
A:Stuck in a visual and audible animation 
B: The trinket can NOT be used (you wont gain the spellpower buff) at all!

**To Reproduce**
Equip both trinkets
Use one
Try to use the other 15s after you used the first one
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by whispersz** [comment] 2020-03-23 07:41
Not sure if it's for a future expansion, but on wowhead it says that they share cooldown.

**Comment by Djakamoe** [comment] 2020-04-06 02:06
absolutely should not intended to work like it is

**Comment by beraus** [comment] 2020-05-04 23:37
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087

**Closed by beraus** 2020-05-04 23:37 UTC
