### ISSUE TITLE
Arena Treasure Chest

### ISSUE THREAD

**Issue by Ownedbyimba** [SunstriderEmu/BugTracker#2836] opened 2020-04-09 08:23 UTC
А chest does not appear in the Gurubashi Arena (Arena Treasure Chest), which gives the quest.
https://classic.wowhead.com/object=179697

The chest should appear every 3 hours (0-3-6-9-12 AM / PM).
Today there was even a disconnect just at 6:00, the chest also did not appear.

**Comment by beraus** [comment] 2020-06-13 23:29
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3384

**Closed by beraus** 2020-06-13 23:29 UTC
