### ISSUE TITLE
[Spell] Wound poison should be a binary spell

### ISSUE THREAD

**Issue by SuddenDeath** [SunstriderEmu/BugTracker#1744] opened 2020-01-23 15:16 UTC
Description: Wound poison should be a binary spell

How it currently works: 
Currently wound poison is considered a non-binary spell and is able to partially resist its damage.

How it should work: 
Wound poison should be a binary spell and not be able to partially resist.
It does direct damage and applies a healing reduction debuff.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Binary_spell?oldid=1432574
Watch combat log from any tbc retail video, wound poison never partially resists.

**Comment by Jerrythemagicdog** [comment] 2020-01-23 15:20
Some videos to better understand the issue: 
Pyrilus 4:
https://youtu.be/rEBL5Favl6Y?t=573
Neilyo (the bits where he hits druids with MotW):
https://www.youtube.com/watch?v=eJWNMCD8SMU

https://youtu.be/fT_aZfg9AP0?t=753

More sources welcome!

**Comment by SuddenDeath** [comment] 2020-01-23 15:31
https://www.youtube.com/watch?v=ZTtZHDcM6lc - with combat log.
3:25 onwards

**Comment by Jerrythemagicdog** [comment] 2020-01-23 15:41
Krymu is a Night Elf in this video (10 nature resistance):
Screenshots of him being hit by a Wound Poison (potato quality sorry everyone!):
Once for 72 damage, once for 77 damage
https://imgur.com/a/Z7JegAB

**Comment by kelno** [comment] 2020-01-23 15:52
A valid proof that the spell is binary would be:
Taking one of those videos and listing all the damage done by poison on some period of time (like ~10 samples taken in a row). It should be super obvious that it's a binary if the damage didn't change.

**Comment by sposobniy** [comment] 2020-01-23 17:10
Video where he hits druid , Is it just "Natural Perfection" reduce damage , not resiste

**Comment by SuddenDeath** [comment] 2020-01-23 17:29
@sposobniy yup, if it's resisted it will say (X resisted) after the damage in combat log.

**Comment by Jerrythemagicdog** [comment] 2020-01-23 17:37
That message might have been added at some point during the expansion (unsure when and if true at all, but there were videos from SWP boss kills where the damage didn't add up I hear and no partial resist message was displayed). We have a way of determining if it's true outlined by https://github.com/SunstriderEmu/BugTracker/issues/1744#issuecomment-577742589

**Comment by SuddenDeath** [comment] 2020-01-23 17:44
@Jerrythemagicdog yeah, any video vs an SL lock with felhunter would be sufficient, seeing currently almost every wound gets partially resisted vs an SL lock.

The video I linked on Warmane's bugtracker was of a rogue with combat log attacking an SL lock and having wound entirely resisted 3-4 times and the rest being 100% hits.
Don't remember which video it was but I'll look for it at some point, though because of this I'm 100% sure it's supposed to be binary.

**Comment by SuddenDeath** [comment] 2020-01-23 18:52
https://youtu.be/ZTtZHDcM6lc?t=10m04s 
@10:00 -> 10:45
Wound poison fully resisted a couple of times, other times it's dealing full damage(apart from absorbed from soul link like all his other hits)

**Comment by blblblaz** [comment] 2020-01-23 19:43
confirmed, what we have is wrong, thanks

**Comment by Jerrythemagicdog** [comment] 2020-01-23 19:44
I'm personally still interested in the case with him being hit by the poison and why is the damage different there.

**Comment by hufsa** [comment] 2020-01-24 11:04
> I'm personally still interested in the case with him being hit by the poison and why is the damage different there ([#1744 (comment)](https://github.com/SunstriderEmu/BugTracker/issues/1744#issuecomment-577737455)).

The opposing rogue had just used vanish where the damage is increased. Could be Master of Subtlety.

**Comment by Jerrythemagicdog** [comment] 2020-01-27 15:51
More proof that high resistance targets (Felhunter) were basically immune to poisons: https://youtu.be/ArS1w1jgKw8?t=358

**Comment by kelno** [comment] 2020-01-28 11:40
To dev: SpellMgr::IsBinaryMagicResistanceSpell

**Comment by hufsa** [comment] 2020-01-28 12:12
Gets excluded in the method above because of SPELL_EFFECT_SCHOOL_DAMAGE.

**Comment by kelno** [comment] 2020-01-28 13:01
Fixed with 13259

**Closed by kelno** 2020-01-28 13:01 UTC
Labels: confirmed
