### ISSUE TITLE
Personal rating arena team bug

### ISSUE THREAD

**Issue by bugbugbugmanybugs** [SunstriderEmu/BugTracker#3190] opened 2020-04-30 09:06 UTC
Dear Stuff,
There is a new bug income after we all received AP. We started a new arena team on wednesday and we made 1865 rating arena team which is on the screen and our personal is 1825. With each game we receive less and less points PERSONAL rating. We do not leave arena etc. Please, solve this problem with personal rating and make personal rating same as our team rating. We are not the only one who has this kind of problem. Thanks

https://imgur.com/a/OWMuRZZ

**Comment by SuddenDeath** [comment] 2020-04-30 11:20
Probably not a bug:
https://github.com/SunstriderEmu/BugTracker/issues/3164

Not sure if it's entirely correct atm but getting different personal from team rating was normal after patch 2.4.2 in TBC.

**Comment by kelno** [comment] 2020-05-02 11:49
There has been some update to the rating system which introduced some issues.
Those should be fixed with next server update

**Closed by kelno** 2020-05-02 11:49 UTC
