### ISSUE TITLE
"Quest: Bloodgem Crystals" Bug

### ISSUE THREAD

**Issue by rinosuke0** [SunstriderEmu/BugTracker#3617] opened 2020-06-05 02:12 UTC
**Describe the bug**

the channeling cancels when you use the item, can't complete the casting
**To Reproduce**

1. Cast X on target affected by ...    "Bloodgem Crystals" with the item "Bloodgem Shard"
![Sin título](https://user-images.githubusercontent.com/66446860/83828894-51c78180-a6a7-11ea-99f9-4df2c3f69e12.jpg)

**Comment by beraus** [comment] 2020-06-05 02:13
Thanks, duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2058

**Closed by beraus** 2020-06-05 02:13 UTC
