### ISSUE TITLE
Ending their World quest in Bloodmyst isle cannot be completed

### ISSUE THREAD

**Issue by Mixplit74** [SunstriderEmu/BugTracker#3685] opened 2020-06-12 05:07 UTC
**Describe the bug**
After completing all pre-requisites I start the escort for Ending their World. I can get the npc to go as far as the end area where Sironis is. But when he gets up there he stands and stops responding, enemies also do not aggro him anymore. Then he despawns. He can be spoken to in this state until he despawns but just repeats the same line. Since he will not engage Sironis the quests can not completed. 

**To Reproduce**

1. Complete all pre-requsite quests
2. Click on Demolitionist Legoso and start escort for Ending Thier World.
3. Follow Demolitionist, helping him fight or healing him to make sure he doesnt die while he goes up the path.
4. Reach the top and see him step under the Vector Coil & become unresponsive.

Quest: https://www.wowhead.com/quest=9759/ending-their-world
NPC: https://www.wowhead.com/npc=17982/demolitionist-legoso
**Expected behavior**
When he reaches the top he should engage with the enemy Sironas and adds should spawn. After defeating them the quest should be marked complete and can be turned in at Exarch Admetius in Blood Watch.

**Additional context**
I attempted the quest twice and the exact same thing occurred during both attempts.

**Comment by beraus** [comment] 2020-06-12 15:00
Thanks, duplicate of https://github.com/SunstriderEmu/BugTracker/issues/1956

**Closed by beraus** 2020-06-12 15:00 UTC
