### ISSUE TITLE
Concerted Efforts - not affected by Faction Balance

### ISSUE THREAD

**Issue by nexumus** [SunstriderEmu/BugTracker#3455] opened 2020-05-21 10:06 UTC
**Describe the bug**
Bring 1 Alterac Valley Mark of Honor, 1 Arathi Basin Mark of Honor, 1 Warsong Gulch Mark of Honor and 1 Eye of the Storm Mark of Honor to an Alliance Brigadier General in any Alliance Capital City, or Horde General in any Horde Capital City will grant you 314honor(1) - which is not affected by faction balance - additional 50% ally / 25% horde 

(1) https://wowwiki.fandom.com/wiki/Quest:Concerted_Efforts
- column to the right, says 314honor

**To Reproduce**
bring 4 marks, redeem them - get 314 honor without faction balance bonus

**Comment by InhumanGM** [comment] 2020-05-21 11:29
Duplicate of #3375

**Closed by InhumanGM** 2020-05-21 11:29 UTC
Labels: quest
