### ISSUE TITLE
Hunter scorpid petautocasttoggle macro bugged

### ISSUE THREAD

**Issue by kelyuxx** [SunstriderEmu/BugTracker#3682] opened 2020-06-11 21:10 UTC
**Describe the bug**
When i use my makro to /petautocasttoggle Scorpid Poison(Rank 5) my scorpid is not using his poison anymore (Uptime on the target, autocast activated and 100 Focus). If i rightclick on the ability to activate autocast it works most of the time.

Its the same makro ive used since i started playing here.

**To Reproduce**
1. Duell/Arena whatever
2. /petautocasttoggle Scorpid Poison(Rank 5)
3. Maybe need to deactivate it by rightclicking and Dismiss/call pet some time to get the bug idk

Spell: https://classic.wowhead.com/spell=24640/scorpid-poison
Character: https://endless.gg/armory/character/kelyu

**Additional context**
Experienced today in arena and comfirmed buggy in duell.

**Comment by kelno** [comment] 2020-06-15 15:32
Thanks for reporting!
I couldn't reproduce the issue: https://streamable.com/h8k7nd
However I think I heard about it before. Any idea what could be different in your case?

**Comment by kelyuxx** [comment] 2020-06-15 15:45
Im not sure, im mostly only logging in to do arenas and havent changed my
pet, makros or specc in a while, the bug just randomly happened. Next time
i play ill test it again and if its still bugged im getting a new scorpid,
maybe that will fix it.

Am Mo., 15. Juni 2020 um 17:32 Uhr schrieb Kelno <notifications@github.com>:

**Comment by kelno** [comment] 2020-06-15 15:55
Thanks for answering, it seems to be specifically about the macro, we've got it reproduced now

**Comment by kelno** [comment] 2020-06-15 16:07
Fixed with next server restart

**Closed by kelno** 2020-06-15 16:07 UTC
