### ISSUE TITLE
Paladin Class Quest is not working!!

### ISSUE THREAD

**Issue by kealthas06** [SunstriderEmu/BugTracker#3343] opened 2020-05-12 18:29 UTC
Paladin Last quest For Mount And Blood knight Tabard 

https://www.wowhead.com/quest=9737/true-masters-of-the-light

Problem is that when you kill the npcs it doesn't count your quest as succes and one of the npcs that you have to kill which is a quest giver doesn't become an enemy  ive spent over 400g for the quest line to have the tabard

**Comment by kealthas06** [comment] 2020-05-16 21:31
ANy improvement going on ?

**Comment by InhumanGM** [comment] 2020-05-18 17:00
Duplicate of #2669

**Closed by InhumanGM** 2020-05-18 17:00 UTC
Labels: bug, confirmed, quest
