### ISSUE TITLE
[Track Humanoids] - [Duid] - [Cat form]

### ISSUE THREAD

**Issue by Keritous** [SunstriderEmu/BugTracker#3632] opened 2020-06-07 08:45 UTC
Since Patch 2.0.1, Shapeshifting into cat form would activate [[Track Humanoids]](https://classic.wowhead.com/spell=5225/track-humanoids) Automatically but on this server, it doesn't.

**Comment by InhumanGM** [comment] 2020-06-07 12:58
Duplicate of #3314

**Closed by InhumanGM** 2020-06-07 12:58 UTC
