### ISSUE TITLE
Arena Ruins of Lordaeron  pathing in the middle bugged

### ISSUE THREAD

**Issue by layalaa** [SunstriderEmu/BugTracker#2797] opened 2020-04-07 01:28 UTC
As a druid or Warrior you are not able to charge on top of the Tomb in the middle of Lordaeron Arena, neither you are able to charge an enemy next to the tomb once u standing on top of it. The pathing is not working properly.

**Comment by mayday2013** [comment] 2020-04-07 14:31
Can confirm.

**Comment by Jerrythemagicdog** [comment] 2020-04-09 04:29
Thanks, duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/2700

**Closed by Jerrythemagicdog** 2020-04-09 04:29 UTC

**Comment by kelno** [comment] 2020-04-10 14:44
Fixed with next restart
