### ISSUE TITLE
Missing Diplomat final quest can't be picked up

### ISSUE THREAD

**Issue by blackouths** [SunstriderEmu/BugTracker#3539] opened 2020-05-29 08:25 UTC
Final quest in the chain to speak to Jaina from Archmage Tervosh cannot be obtained. You click on the quest in the quest log and the UI is unresponsive. The quest cannot be picked up.

This has persisted through /reload and through a relog.

**Comment by beraus** [comment] 2020-06-13 23:58
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2116

**Closed by beraus** 2020-06-13 23:58 UTC
Labels: quest
