### ISSUE TITLE
Cooking Recipes missing from Vendors

### ISSUE THREAD

**Issue by Varde9896** [SunstriderEmu/BugTracker#2132] opened 2020-03-06 07:21 UTC
**Describe the bug**
Juicy Bear Burger Recipe missing from Bale in Felwood. Others too ( I forgot which ones where)

**To Reproduce**
1. Go to Vendor and find no item
2. Be confused
https://tbc-twinhead.twinstar.cz/?item=35566

**Expected behavior**
Recipes should be there

**Comment by SUN-Leekie** [comment] 2020-03-06 18:17
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2011

**Closed by SUN-Leekie** 2020-03-06 18:17 UTC
