### ISSUE TITLE
The smallest Creatures quest

### ISSUE THREAD

**Issue by Phatmeme** [SunstriderEmu/BugTracker#3711] opened 2020-06-14 23:13 UTC
**after using the kodohide drum and controlling the marmot all enemies are invisible. second, when trying to use the marmot ability to poison the kegs, nothing happens. trying to click on the kegs themselves it just says "you are to far away"**

**Comment by beraus** [comment] 2020-06-14 23:15
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2022

**Closed by beraus** 2020-06-14 23:15 UTC

**Comment by Lamberdo** [comment] 2020-06-29 08:56
not working at this time ;/ same reason
