### ISSUE TITLE
Zepelin bug

### ISSUE THREAD

**Issue by AWIDIUS** [SunstriderEmu/BugTracker#1859] opened 2020-02-16 10:04 UTC
When zepelin is deported from STV it appears in durotar, but it stays in air and not moving and mobs on zepelin seems to fall down on ground, maybe visual bug, dunno
![image](https://user-images.githubusercontent.com/45521546/74602706-05324900-50ac-11ea-8ce0-0b881c7f8e55.png)

**Comment by AWIDIUS** [comment] 2020-02-16 10:05
![image](https://user-images.githubusercontent.com/45521546/74602728-3874d800-50ac-11ea-9e9d-df5ad5e8e6ff.png)
Im bugged on it, unable to move
takes around 10 sec to ship to move

**Comment by Jerrythemagicdog** [comment] 2020-02-16 14:36
Thanks, duplicate of: https://github.com/SunstriderEmu/BugTracker/issues/1859

**Closed by Jerrythemagicdog** 2020-02-16 14:36 UTC
