### ISSUE TITLE
Gnomish Death Ray

### ISSUE THREAD

**Issue by Itslunartiik** [SunstriderEmu/BugTracker#2986] opened 2020-04-16 03:26 UTC
**Describe the bug**

When i use the gnomish death ray trinket taught through gnomish engineering, it channels the trinket/ability like it should but deals no damage at the end of channelling. Below is a screen shot of what it should look like once its finished channelling.
https://wow.zamimg.com/uploads/screenshots/normal/65365-gnomish-death-ray-a-gnomish-death-ray-unleashing-on-a-boulderfist-ogre.jpg

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item= https://classic.wowhead.com/item=10645/gnomish-death-ray#created-by-spell
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Once you activate the trinkets ability it should channel as it does and then once its finished channelling it should do a random amount of damage, in this case it does nothing at the end of channeling. Again Screenshot of what it should look like.

https://wow.zamimg.com/uploads/screenshots/normal/65365-gnomish-death-ray-a-gnomish-death-ray-unleashing-on-a-boulderfist-ogre.jpg
**Screenshots/videos**

**Additional context**

I have tried the trinket on multiple level 62 NPC's and 2-3 level 9 NPC's and still the problem of NO damage occurs. Which tells me its not a level issue.

**Comment by hashblaster** [comment] 2020-04-16 05:06
This has been confirmed since Mar 19, 2019.   Super disappointing to level engineering & have stuff not work.  Battle chicken doesn't do any damage either.

**Comment by Itslunartiik** [comment] 2020-04-16 18:44
yeah its a real shame i enjoy engineering especially in PVP, we had any news on if its being looked into or even considered for fixing?

**Comment by hashblaster** [comment] 2020-04-19 00:21
They have bigger problems I imagine

**Comment by beraus** [comment] 2020-05-31 01:41
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/799

**Closed by beraus** 2020-05-31 01:41 UTC
