### ISSUE TITLE
Stormwind Rendezvous

### ISSUE THREAD

**Issue by EneaMapelli** [SunstriderEmu/BugTracker#2939] opened 2020-04-13 07:04 UTC
After freeing Windsor from brd I should be able to summon him to stormwind by talking to Squire Rowe at the gates of the city. Squire Rowe does not present the line of dialogue needed to invoke Windsor.

**Comment by beraus** [comment] 2020-08-11 03:21
https://github.com/SunstriderEmu/BugTracker/issues/2592

**Comment by z5n** [comment] 2023-07-10 23:15
duplicate of #5153

**Closed by z5n** 2023-07-10 23:15 UTC
Labels: quest
