### ISSUE TITLE
Val'Zareq the Conquerer, Elite quest mob in Shadowmoon Valley is bugged

### ISSUE THREAD

**Issue by Perkycrits** [SunstriderEmu/BugTracker#2774] opened 2020-04-05 23:40 UTC
Val'Zareq the Conquerer, Elite quest mob in Shadowmoon Valley is bugged. Upon killing him, he completely disappears and doesn't have a body to loot or anything. You're supposed to kill him to start the quest chain for the illidari tabard. Which I've seen plenty of people who have it, so I'm not sure what the problem with this mob is right now.

**Comment by Jerrythemagicdog** [comment] 2020-04-09 05:29
From what I see he's linked to his formation members that requires you to kill the entire formation or the individual members respawn.

**Comment by Perkycrits** [comment] 2020-04-09 07:48
I was in a group and we killed him and his blood knights, still nothing.

**Comment by beraus** [comment] 2020-05-27 02:25
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/3008

Couldn't reproduce.

**Closed by beraus** 2020-05-27 02:25 UTC
