### ISSUE TITLE
[quest] Kindness doesn't give credit ~75% of the time

### ISSUE THREAD

**Issue by babno** [SunstriderEmu/BugTracker#3647] opened 2020-06-08 03:30 UTC
Title. Currently 3/8 after using 14 carcasses

**Comment by beraus** [comment] 2020-06-08 04:04
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2549
Dev note: 2 days 19 hours online.

**Closed by beraus** 2020-06-08 04:04 UTC
