### ISSUE TITLE
Scryer's Bloodgem and Xi'Ri's Gift share the same 1m30s cooldown

### ISSUE THREAD

**Issue by recreantus** [SunstriderEmu/BugTracker#2886] opened 2020-04-10 20:50 UTC
**Describe the bug**
When you have both Scryer's Bloodgem and Xi'ri's Gift equipped and activate one of them, you can't use the other one for a full 1m30s, once the first trinket cooldown has finished. You should only have to wait for the duration of the first trinket (15 sec) before being able to activate the next. When you try to use the second trinket after 15 seconds your character seems to initiate the animation but nothing happens.

**To Reproduce**
1. Use Scryer's Bloodgem
2. Wait 15 seconds, then try to use Xi'ri's Gift
3. See how the character beings to cast it, but nothing happens

Item: https://tbc-twinhead.twinstar.cz/?item=29179
Item: https://tbc-twinhead.twinstar.cz/?item=29132

**Expected behavior**
After having used one of the trinkets, after 15 seconds you should be able to activate the other one. Instead here you have to wait for the first trinket cooldown to finish before you can use the other one, rendering it completely useless.

**Screenshots/videos**
https://www.youtube.com/watch?v=KTIy-gb93kk

**Additional context**

**Comment by beraus** [comment] 2020-04-10 22:22
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087

**Comment by whispersz** [comment] 2020-04-11 06:49
Its not a bug. if you click on use buff of one trinket you will see that you get same thing from second.
![image](https://user-images.githubusercontent.com/47157488/79037441-a7b50700-7bd9-11ea-8f93-bd030bbb2961.png)

**Comment by recreantus** [comment] 2020-04-11 12:25
> Its not a bug. if you click on use buff of one trinket you will see that you get same thing from second.
> ![image](https://user-images.githubusercontent.com/47157488/79037441-a7b50700-7bd9-11ea-8f93-bd030bbb2961.png)

I don't really know what you're trying to say there, whispersz. But yes, they have the same on-use effect, but they should not share the same 1.5m cooldown. You should be able to use them both within 15 seconds

**Comment by whispersz** [comment] 2020-04-11 15:13
I am saying it's not a bug. In the printscreen of my earlier post i demonstrated you that the "use" effect of both trinkets is the same. That means you cannot use both trinkets.
For example, if you click on the use effect Icon of the Silver Crescent, you will see that its not used by anything else. Therefore you can use Icon of the Silver Crescent and Xiri Gift or Icon of the Silver Crescent and Scryer's Bloodgem.
![image](https://user-images.githubusercontent.com/47157488/79047568-2765c480-7c20-11ea-8c44-b680644c7364.png)

**Comment by Balanarr** [comment] 2020-04-13 07:44
> I am saying it's not a bug. In the printscreen of my earlier post i demonstrated you that the "use" effect of both trinkets is the same. That means you cannot use both trinkets.
> For example, if you click on the use effect Icon of the Silver Crescent, you will see that its not used by anything else. Therefore you can use Icon of the Silver Crescent and Xiri Gift or Icon of the Silver Crescent and Scryer's Bloodgem.
> ![image](https://user-images.githubusercontent.com/47157488/79047568-2765c480-7c20-11ea-8c44-b680644c7364.png)

He's not talking about using both at the same time though. He's saying that using one triggers the full cooldown on both. Should only trigger a cooldown equal to the buff duration for the one that wasn't used.

**Comment by whispersz** [comment] 2020-04-13 10:46
I've never said that they should work at the same time or should not work at the same time.
I just said they cannot work as you guys are suggesting.  You can have those trinkets equipped for passive stats and you can use only one. That is how it was intended to work.
What part of shared CD on the use effect is so hard to understand?

**Comment by beraus** [comment] 2020-05-04 23:38
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2087

**Closed by beraus** 2020-05-04 23:38 UTC
