### ISSUE TITLE
Lockbox Not Giving Loot

### ISSUE THREAD

**Issue by Mememeistur** [SunstriderEmu/BugTracker#3715] opened 2020-06-15 19:43 UTC
I've had a few lockboxes opened so far, and it seems not a single one has given loot, i've also asked guildies and it seems they have had the same experience, I don't know if we're just all very unlucky or it's a bug but it's worth it to report it.

**Comment by beraus** [comment] 2020-06-16 01:25
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2368

**Closed by beraus** 2020-06-16 01:25 UTC
