### ISSUE TITLE
Rocket Boots Xtreme Bug

### ISSUE THREAD

**Issue by scorchlebg** [SunstriderEmu/BugTracker#2871] opened 2020-04-10 09:52 UTC
**Describe the bug**

When using the Rocket Boots Xtreme (leather) you have a small chance to be stuck for 3 seconds. But on this server it actually break every single time and it's pretty frustrating.

**To Reproduce**

1. Use the rock boots extrem
2. See 
3. 

Item:  https://www.wowhead.com/item=23824/rocket-boots-xtreme#created-by-spell
**Expected behavior**

To not break every single time

**Screenshots/videos**

https://youtu.be/JCSu-jUCNps (me recording)
https://www.youtube.com/watch?v=jdYTYIQdCd0 (tbc clip where the rocket boots doesn't break)

**Comment by beraus** [comment] 2020-05-05 00:02
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2500

**Closed by beraus** 2020-05-05 00:02 UTC
