### ISSUE TITLE
healthy dragonscale quest scholomance

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#3709] opened 2020-06-14 16:33 UTC
each of the dragon whelps in scholomance drops a quest item "healthy dragon scale" which when clicked gives you the quest "Healthy Dragon Scale".   I can not accept the quest.  "You don't meet the requirements for that quest".

if i dont meet the requirements, i shouldn't be looting it.  2-3 months ago, i accepted the quest fine, but for some reason now (faction too high maybe?) I can't accept it anymore.

also, a bit ridiculous to be able to loot 20-30x of these scales pulling one room... (which is why i want to do the quest so they no longer drop for me).

**Comment by z5n** [comment] 2022-05-31 13:55
Duplicate of #4535

**Closed by z5n** 2022-05-31 13:55 UTC
