### ISSUE TITLE
Entering falling state after riding a gryphon and descending down terrain will cause fall damage.

### ISSUE THREAD

**Issue by plutonium447** [SunstriderEmu/BugTracker#848] opened 2019-03-23 12:04 UTC
**Description:**
After flying on a gryphon/wyvern/hippogryph for a long duration (approx 7mins +) it is possible for the player to recieve fall damage after entering a fall state. The amount of fall damage dealt can be more than the players health. Several players on the server have been killed by this issue.

This can be triggered either through falling from a non-lethal height - but nontheless puts the player character into the "falling" animation - or by "bumping" into an object on the ground, which can cause the player to momentarially enter a falling state.

**Current behaviour:**
After travelling a long distance on a flightmaster and then falling a small distance, it is possible for the player to be killed by a large amount of fall damage.

![Screenshot from 2019-03-23 19-37-35](https://user-images.githubusercontent.com/40911527/54865786-9cb4ec00-4db6-11e9-9229-2fc33d06ab9f.jpg)
Fig.1 _I flew from theramore to felwood and this was the first time i entered a fall state and took damage_

![Screenshot from 2019-03-23 21-00-16](https://user-images.githubusercontent.com/40911527/54865788-a0e10980-4db6-11e9-8f91-77688af522d3.jpg)
Fig.2 _an example of the fall damage triggering. it is not caused by map geometry as i can use different objects to create the fall state_

![Screenshot from 2019-03-23 21-25-54](https://user-images.githubusercontent.com/40911527/54865790-a50d2700-4db6-11e9-927f-2292545fea7e.jpg)
Fig.3 _another example_

![Screenshot from 2019-03-23 21-54-47](https://user-images.githubusercontent.com/40911527/54865792-a9394480-4db6-11e9-808b-05edd72133f3.png)
Fig.4 _the route traveled by the player which contributed to the issue_

**Expected behaviour:**
Players should not suffer large amounts of fall damage from small falls after travelling a long distance on a flightmaster

**Steps to reproduce the problem:**

1. Be alliance.
2. Go to Theramore Isle FP.
3. Fly to Talonbranch Glade FP, in Felwood.
4. Mount up, run to location in Fig.2, not far from FP location.
5. Run over the root of the tree, causing momentary fall state
6. Recieve fall damage.
7. If no fall damage recieved, fly to Talonbranch Glade from a further location and try again.

This issue is somewhat rare, occuring to players only after having travelled by flightmaster from a long distance. Most players will only recieve a small amount of damage, and not even notice the damage that occured. But when the conditions are correct, players will sometimes find themselves being instantly killed after bumping into a rock on the ground.

**Related Issues**
https://github.com/thebarrensissues/Issues/issues/812

**rev. hash/commit:**
**rev. 10718**

edit: spelling, clarity reasoning

**Comment by kelno** [comment] 2019-03-24 04:13
Very nice, thanks for the many details here

**Comment by plutonium447** [comment] 2019-03-24 12:49
**Update**
I found the precise source of the bug, and can accurately replicate it on demand.

1. Be Alliance
2. Go to Thelsamar FP, Loch Modan.
3. Fly to Ironforge FP.
4. Land in Ironforge.
5. Run out of Ironforge, not falling or bumping into objects.
6. Run all the way down to pic related:
![Screenshot from 2019-03-24 22-17-01](https://user-images.githubusercontent.com/40911527/54879440-b58bd300-4e84-11e9-89a3-7554d679e24b.jpg)

7. **Important**: Run directly at the small stone fence post at a 45 degree angle. This will cause the player to jump up slightly into the air and fall back down, while sliding off the object and doing so at great speed.
![Screenshot from 2019-03-24 22-44-51](https://user-images.githubusercontent.com/40911527/54879618-b9205980-4e86-11e9-8f9c-794ef967faf5.png)

8. Die.
![Screenshot from 2019-03-24 22-24-03](https://user-images.githubusercontent.com/40911527/54879470-03a0d680-4e85-11e9-9a2f-7720b8115a19.png)

**Discussion**
What i think is occuring here, is that when the player lands from a gryphon their falling state is not correctly set, causing the game to think that the player is currently falling while on the ground. When the player decends down the terrain and at some point snags against an object on the ground (post, rock, tree, box) the game then thinks that the player has landed, and calculates the vertical distance from where the player landed at the flightmaster, and where the player currently landed. In this example, the distance is enough to easily kill the player. This was done when the player ran out of ironforge and descended down the large slope into Dun Morogh.

Hopefully the above method works consistantly for the bug to be replicated, otherwise im probably gonna blow my brains out. took me like 3 hrs to get a working step list for this dumb bug to kill me over and over. like fuck

palla out
*drops mic*

**Comment by Tamosheik** [comment] 2019-03-31 03:37
This bug also appears to affect the lift at Telredor in Zangarmarsh

**Comment by Killabean** [comment] 2019-04-04 01:59
And the Freewind Post lift.  I had formed the (possibly incorrect) opinion that the bug was related to a more general "lag" in the game's record of the players altitude.  Possibly related to #835.  
All the cases I recall _were_ after flying, sometimes many minutes.  It does seem to require a small "fall" to trigger the falling damage/death.  I have not yet included flying in my failed attempts to reproduce the issue.

**Comment by Jerrythemagicdog** [comment] 2019-10-28 01:37
Tested in these places, doesn't happen anymore.
Possibly fixed with "2651e3d3eb97de701d8a3df71dbe0d5bb517b129" (core)

**Closed by Jerrythemagicdog** 2019-10-28 01:37 UTC
Labels: confirmed, core, gamebreaking

**Comment by kelno** [comment] 2019-10-28 09:51
I couldn't reproduce it in the first place even before so I'm not sure, but it could be it was fixed and it wasn't reported in a while so let's keep it closed for now.
(That commit for sure isn't the cause though)
