### ISSUE TITLE
[Item] - 2 Trinkets sharing 1.5 Minute cooldown

### ISSUE THREAD

**Issue by Cheelout** [SunstriderEmu/BugTracker#1050] opened 2019-04-08 09:15 UTC
**Description:**

The following trinkets are sharing the full 1.5 minute cool down even though the 2nd one goes on CD for 15 seconds.

https://www.wowhead.com/item=29179/xiris-gift
https://www.wowhead.com/item=29132/scryers-bloodgem

I believe they are sharing this cooldown because of this buff that each trinket grants: http://tbc.cavernoftime.com/spell=35337

**Current behaviour:**

The following trinkets are sharing the full 1.5 minute cool down even though the 2nd one goes on CD for 15 seconds.

https://www.wowhead.com/item=29179/xiris-gift
https://www.wowhead.com/item=29132/scryers-bloodgem

I believe they are sharing this cooldown because of this buff that each trinket grants: http://tbc.cavernoftime.com/spell=35337

**Expected behaviour:**

Trinkets should only share a 15 second (Duration of the other buff) Cooldown

**Steps to reproduce the problem:**

1. Equip both trinkets
2. Use one and wait 15 seconds
3. Try use other

![image](https://user-images.githubusercontent.com/38281939/55712704-910e2a00-5a32-11e9-9a4a-f99d981483b2.png)

**Comment by Jerrythemagicdog** [comment] 2019-10-26 22:04
They are indeed using the same spell, which also makes the buffs not stack.
The cooldown is not supposed to be shared, though (confirmed by a wowhead post):
https://www.wowhead.com/item=29179/xiris-gift#comments:id=284572

**Comment by knoxz** [comment] 2020-04-21 23:06
Any updates on this? Kind of an old Bug... It is still ingame :-(

**Comment by InhumanGM** [comment] 2020-05-17 03:34
Duplicate of #2087

**Closed by InhumanGM** 2020-05-17 03:34 UTC
Labels: confirmed, core
