### ISSUE TITLE
Alliance First Aid from 225 --> 300 is not possible.

### ISSUE THREAD

**Issue by Krykutay** [SunstriderEmu/BugTracker#2727] opened 2020-04-03 19:44 UTC
I'm level 70 with 225 First Aid skills. However, the npc Doctor Gustaf VanHowzen isn't targettable. Thus, I can't take the first aid quest from him. I've been seeing a lot of people not being able to speak with this guy.

**Comment by beraus** [comment] 2020-04-03 19:56
Temp fixed.

**Comment by beraus** [comment] 2020-04-03 20:04
Duplicate of https://github.com/SunstriderEmu/BugTracker/issues/2444.
Temp fixed.

**Comment by tamerechien** [comment] 2020-04-03 20:15
Still bugged.

**Comment by tamerechien** [comment] 2020-04-03 20:20
yeah and killing him dosen't help with the problem to be honest.

**Comment by reli21** [comment] 2020-04-06 13:09
how to raise FA without talking to him?

**Comment by reli21** [comment] 2020-04-06 19:47
Fixed

**Comment by Jerrythemagicdog** [comment] 2020-04-29 03:50
Thanks, fixed with next restart!

**Closed by Jerrythemagicdog** 2020-04-29 03:50 UTC
