### ISSUE TITLE
[Hunter] Multi-shot chain range is too small

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#4217] opened 2020-09-15 19:43 UTC
**Describe the bug**
Maximal Multi-shot chain distance on endless right now:
![image](https://user-images.githubusercontent.com/45561230/93256010-fecb9300-f79a-11ea-92c9-c44a5ae44798.png)

Same issue has chain lightning which also has this tiny range to chain between targets. (they should be both same, wont be making seperate report for it)

**Expected behavior**
Multi-shot and chain lightning chain range should be larger. This is how maximal distance looks on good servers
![image](https://user-images.githubusercontent.com/45561230/93256376-8f09d800-f79b-11ea-9f88-3652720b1850.png)

And these are videos from tbc where you can actualy see that the range is definetly bigger to what endless currently has

https://youtu.be/9qv4nbt-NNk?t=158 Look at distance between rogue and water ele

https://www.youtube.com/watch?v=VhCI3DDvGGU&start=733

https://youtu.be/VhCI3DDvGGU?t=1059

**Comment by Aeded** [comment] 2020-09-15 19:46
In case you decide to shove this report along with many others "under the rug" atleast have the decency and include it in your list of custom changes so people who want to play blizzlike server dont get lured here and waste their time. Thanks

**Comment by Jerrythemagicdog** [comment] 2020-09-15 22:42
Chain Lightning:
![ChainLightning](https://user-images.githubusercontent.com/46463908/93271895-40186e80-f7ac-11ea-9d0a-126d1130da16.png)

Multi-Shot:
![MutliShot](https://user-images.githubusercontent.com/46463908/93271917-4c043080-f7ac-11ea-95ae-cebfe4a8fd97.png)

Keeping in mind that "hitbox" sizes are universal and don't vary from race to race this seems correct, after some googling there doesn't seem to be much information as to what the chain range of Multi-Shot is.

There seems to be an issue which the first video (https://youtu.be/9qv4nbt-NNk?t=158) shows that can be seen in this picture as well: 
![ChainingMiddle](https://user-images.githubusercontent.com/46463908/93272198-e2d0ed00-f7ac-11ea-8840-6bbb5cbdc8b8.png)
If the Hunter was to Multi-Shot the dummy on the left the Multi-Shot would only chain to the dummy in the middle, same as if he were to Multi-Shot the dummy on the right it would only chain to the dummy in the middle which doesn't seem correct.

**Comment by bluemanguy112** [comment] 2020-09-15 23:08
https://www.youtube.com/watch?v=35DPcNmAp8o&start=1232

I could go on with endless clips of similar situations. I think at this points it is up to you guys to either provide clips confirming your version or just adjusting it to the values shown in these. I don't understand why this is getting challenged this hard anyway This is nothing gamebreaking, whereas some thigs seem to get changed on a whim. Togther with #4220 (which is marked as 'Confirmed' for 7 months at this point), it makes highest hitting PvP ability quite bad.

**Comment by Jerrythemagicdog** [comment] 2020-09-15 23:45
Other servers are not proof for how anything should work. 
There seems to be an issue with what that was described above, maybe we'll get to something else once we start looking at it, but if we're trying to emulate retail then it would be great to actually get some information as to what the range is (discounting for hitbox sizes).

**Comment by bluemanguy112** [comment] 2020-09-15 23:55
Some guy literally provided a clip from Classic WoW in #4064 (btw who is this guy that closes not fixed bugs?). Anyway the range in that Clip (as well as the other Server) would suggest it to be somewhere in the 10-12y range. To fully confirm this someone would need to check this with a Range addon on Classic (or is this not considered a viable Source?).

https://www.youtube.com/watch?v=zPGJ7pm77eE

**Comment by Jerrythemagicdog** [comment] 2020-09-15 23:58
Definitely good enough proof, thanks!

**Comment by bugreport4** [comment] 2020-09-16 15:01
What about trap radius? It was reported during beta (with more than enough proof), and still not fixed?

**Comment by Eykoendless** [comment] 2020-09-16 21:54
The chain distance for multishot depends entirely on the angle the hunter shoots at aswell as the distance between targets. It behaves as any other cone ability. Whenever you use it you have to think about what's your position in relation to your targets, which way are you facing, and what's the distance between you and your main target since that will determine the final "width" of the cone.

It is working as it should as far as my experience goes.

**Comment by bluemanguy112** [comment] 2020-09-16 21:56
Wrong, it is not a cone ability. It works like Chainlighning does.

**Comment by bluemanguy112** [comment] 2020-09-16 22:11
https://github.com/netherspite/cc-buglist/issues/626

Additional Info: Multi-Shot should ignore Min- as well as Maxrange restrictions, but should never hit targets behind the Hunter (as provided by #4218). Not sure if this is currently behaving the correct way here.

**Comment by bugreport4** [comment] 2020-09-17 08:01
https://youtu.be/NoKD723_yAM?t=414

**Comment by bugreport4** [comment] 2020-09-17 12:37
Also it's not functioning like a chain ability. Only the main target is checked for "jumps" on Endless. (also reported during the beta -_-)

**Comment by bluemanguy112** [comment] 2020-09-19 16:19
Any update of this getting fixed together with #4218 #2646 #4220 ? This is quite a massive issue for Hunters in Arena PvP and deserves some higher Prio.

**Comment by bluemanguy112** [comment] 2020-09-26 09:57
Update on a potential fix?

**Comment by bluemanguy112** [comment] 2020-10-10 17:56
Still not fixed.

**Comment by Jerrythemagicdog** [comment] 2021-02-08 00:50
Thanks for the issue, fixed with next update.

**Closed** 2021-02-08 00:50 UTC
Labels: core, question
