### ISSUE TITLE
Quest: Beer Basted Boar Ribs missing header

### ISSUE THREAD

**Issue by atmichalak** [SunstriderEmu/BugTracker#2937] opened 2020-04-13 01:01 UTC
**Describe the bug**
Quest Beer Basted Boar Ribs is missing its quest header to place it correctly in the quest journal.

**To Reproduce**
Pick up quest in Kharanos to see the incorrect header.

Quest: https://classic.wowhead.com/quest=384/beer-basted-boar-ribs

**Expected behavior**
Expected to see the quest listed as a Dun Morogh quest.

**Comment by hashblaster** [comment] 2020-04-13 08:04
Plz don't bog down the bugtracker with trivial stuff we have lots of big problems

**Comment by beraus** [comment] 2020-07-05 04:29
Couldn't reproduce, clear your cache.

**Comment by beraus** [comment] 2020-07-13 02:14
![image](https://user-images.githubusercontent.com/16673248/87264087-67f30980-c4bf-11ea-8573-694be1248b33.png)

**Comment by Jerrythemagicdog** [comment] 2020-07-13 02:27
Thanks, fixed with next update.

**Closed by Jerrythemagicdog** 2020-07-13 02:27 UTC
Labels: low priority, quest
