### ISSUE TITLE
Impossible to auction Items with Charges 

### ISSUE THREAD

**Issue by Sjoen** [SunstriderEmu/BugTracker#3141] opened 2020-04-26 15:34 UTC
**Describe the bug**
Not able to put item with 10 charges on AH, even if it is unused. The item is [Thick Felsteel Necklace]

**To Reproduce**
When i try to post it on AH i get the following Error code from AH: "Cannot auction an Item with used charges"

**Expected behavior**
It should be possible to action this when unused.

**Screenshots/videos**
![Skjermbilde](https://user-images.githubusercontent.com/64368113/80312196-24ec9880-87e4-11ea-849b-335425004baa.PNG)

**Additional context**

**Comment by InhumanGM** [comment] 2020-06-01 18:56
Duplicate of #3475

**Closed by InhumanGM** 2020-06-01 18:56 UTC
